# vim: ai et ts=2 st=2 sw=2 :
---
- name: Base server configuration
  hosts: base
  become: true

  tasks:
    - name: Set node hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname.split(".") | first }}'
        use: systemd

    - name: Update cache and install some packages, even on check mode
      ansible.builtin.apt:
        name:
          - git
          - libnss-mdns
        update_cache: true
      check_mode: false

    - name: Set SSH keys
      ansible.posix.authorized_key:
        user: '{{ ansible_user }}'
        key: '{{ authorized_key }}'
        exclusive: true
      become: false
      tags:
        - ssh

    - name: Allow other things
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: '{{ base_ufw_rules | default([]) }}'

    - name: Add cron jobs
      ansible.builtin.cron:
        name: '{{ item.name }}'
        weekday: '{{ item.weekday | default(omit) }}'
        day: '{{ item.day | default(omit) }}'
        minute: '{{ item.minute | default(omit) }}'
        hour: '{{ item.hour | default(omit) }}'
        user: root
        job: '{{ item.job }}'
        state: '{{ item.state | default("present") }}'
      loop: '{{ base_cron | default([]) }}'
      tags:
        - cron

    - name: Server ssh notify
      ansible.builtin.template:
        src: sshnotif
        dest: /usr/local/bin/sshnotif
        mode: '0755'

    - name: Add notify on ssh
      ansible.builtin.lineinfile:
        path: /etc/pam.d/common-session
        line: session optional pam_exec.so /usr/local/bin/sshnotif
      when: ansible_os_family | lower == "debian"

    - name: Add notify on ssh
      ansible.builtin.lineinfile:
        path: /etc/pam.d/sshd
        line: session optional pam_exec.so /usr/local/bin/sshnotif
      when: ansible_os_family | lower == "redhat"

    - name: Checkout notes repository containing powerline
      ansible.builtin.git:
        repo: 'https://github.com/aheimsbakk/notes.git'
        dest: /tmp/notes-git
        version: master

    - name: Install dependencies for powerline
      ansible.builtin.command: /tmp/notes-git/install-powerline-go.sh
      args:
        creates: /etc/profile.d/z-powerline-go.sh

    - name: Copy custom scripts
      ansible.builtin.copy:
        dest: '/usr/local/bin/{{ item | split(".") | first }}'
        src: '{{ item }}'
        mode: '0755'
      loop:
        - departure.sh
        - git-touch.sh
