---
- name: configure k3s master
  hosts: master_node
  become: true

  vars:
    deployment_path: /root/deployments

  tasks:
    - name: copy out all deployment/base
      copy:
        src: "{{ item }}/base"
        dest: "{{ deployment_path }}/{{ item }}/"
        mode: 0600
        directory_mode: 0700
      loop: &deployments
        - traefik
        - pod-updater
        - gitlab
        - gitlab-runner
        - gotify
        - munin
        - nextcloud
        - smokeping
        # - pihole
        - diun

    - name: "copy out all for env '{{ env }}'"
      copy:
        src: "{{ item }}/{{ env }}"
        dest: "{{ deployment_path }}/{{ item }}/"
        mode: 0600
        directory_mode: 0700
      loop: *deployments

    - name: "apply depolyments env '{{ env }}'"
      command: "kubectl apply -k {{ deployment_path }}/{{ item }}/{{ env }}"
      changed_when: true
      loop:
        - traefik
        - gitlab
        - gitlab-runner
        - gotify
        - munin
        - nextcloud
        - smokeping
        # - pihole
        - diun

    - name: "apply pods-updater in env '{{ env }}'"
      command: "kubectl -n {{ item }} apply -k {{ deployment_path }}/pod-updater/{{ env }}"
      changed_when: true
      loop:
        - default
        - traefik
        - build
