---
- name: configure k3s master
  hosts: k3s_master
  become: true

  vars:
    deployment_path: /root/deployments

  tasks:
    - name: copy out deployment
      ansible.builtin.copy:
        src: "{{ item }}/"
        dest: "{{ deployment_path }}/{{ item }}/"
        mode: 0600
        directory_mode: 0700
      loop:
        - base
        - deployment
        - '{{ env }}'

    - name: "apply depolyments env '{{ env }}'"
      ansible.builtin.command: "kubectl apply -k {{ deployment_path }}/{{ env }}"
      changed_when: true
