---
- name: Configure k3s master
  hosts: k3s_master
  become: true

  vars:
    deployment_path: /root/deployments

  tasks:
    - name: Copy out deployment
      ansible.builtin.copy:
        src: "{{ item }}/"
        dest: "{{ deployment_path }}/{{ item }}/"
        mode: 0600
        directory_mode: 0700
      loop:
        - base
        - deployment
        - '{{ env }}'

    - name: "Apply depolyments env '{{ env }}'"
      ansible.builtin.command: "kubectl apply -k {{ deployment_path }}/{{ env }}"
      changed_when: true

    - name: Remove deployment files
      ansible.builtin.file:
        path: "{{ deployment_path }}"
        state: absent
