# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure fedora desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on fedora
      assert:
        that: ansible_distribution == "Debian"

    - name: install packages
      apt:
        name:
          # - etckeeper         # Watch what happens in /etc
          # - gnome-tweaks      # Customize Gnome
          # - gnupg-pkcs11-scd  # Smart card functionality for SSH keys on Yubikey
          # - keepassxc         # KeePass
          # - pam-u2f           # U2F token 2 factor in PAM
          # - pamu2fcfg         # Set up U2F token
          # - pcsc-lite         # Smart card daemon
          # - syncthing         # To sync stuff
          # - u2f-host          # Commandline U2F operations
          # - virt-manager      # Graphical interface to Libvirt
          # - whois             # A must
          # - wireguard-tools   # Wireguard VPN
          # - yamllint          # YAML files need to be linted too
          # - yubikey-personalization-gui  # Yubico configuration
          # - yubioath-desktop  # The Yubico Authenticator
          - btrfs-heatmap     # Visualize how data is stored on disk
          - catimg            # Display images in terminal
          # - compsize          # Check the compression ratio on btrfs
          - davfs2            # DavFS for mounting Nextcloud, no need to sync everything
          - dstat             # Stat system values in colors
          - duperemove        # Dedup btrfs
          - ffmpeg            # Transcode audio and video
          - file              # What file is this?
          - flac              # Lossless audio
          - git               # Version control <3
          - hugo              # Static blog generator
          - lame              # Encode mp3
          - lftp              # FTP isn't dead
          # - ltrace            # Trace library calls
          - mediainfo         # Used by AAX
          - ncdu              # Interactive du
          - nmap              # Scan network ports
          - offlineimap       # Make local backup of IMAP
          - pv                # How fast do we transfer
          - python3-pygments  # Syntax highlighting in Hugo
          - python3-qrcode    # Generate QR-codes in terminal with qr
          - rsync             # Syncing files, syncing life
          - strace            # String trace processes
          - tmux              # <3
          - vim               # <3
          - zmap              # Map internet

    - name: flatpak remote flathub
      flatpak_remote:
        name: flathub
        state: present
        method: user
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      become: false

    - name: flatpak remote fedora
      flatpak_remote:
        name: fedora
        state: present
        method: user
        flatpakrepo_url: oci+https://registry.fedoraproject.org
      become: false

    - name: install flatpaks from flathub
      flatpak:
        name: '{{ item }}'
        remote: flathub
      become: false
      loop: []
        # - com.belmoussaoui.Decoder
        # - com.calibre_ebook.calibre
        # - com.github.micahflee.torbrowser-launcher
        # - com.github.phase1geo.minder
        # - com.github.tchx84.Flatseal
        # - com.nextcloud.desktopclient.nextcloud
        # - fr.handbrake.ghb
        # - io.github.quodlibet.ExFalso
        # - net.supertuxkart.SuperTuxKart
        # - org.audacityteam.Audacity
        # - org.chromium.Chromium
        # - org.duckstation.DuckStation
        # - org.gabmus.whatip
        # - org.gimp.GIMP
        # - org.gnome.Dictionary
        # - org.gnome.Epiphany
        # - org.gnome.Evince
        # - org.gnome.Extensions
        # - org.gnome.FileRoller
        # - org.gnome.Maps
        # - org.gnome.Shotwell
        # - org.gnome.TextEditor
        # - org.gnome.Todo
        # - org.gnome.gitlab.somas.Apostrophe
        # - org.mozilla.Thunderbird
        # - org.mozilla.firefox
        # - org.remmina.Remmina
        # - org.signal.Signal
        # - org.supertuxproject.SuperTux
        # - org.videolan.VLC

    - name: install flatpaks from fedora
      flatpak:
        name: '{{ item }}'
        remote: fedora
      become: false
      loop: []

