# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure ubuntu desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on ubuntu
      assert:
        that: ansible_distribution == "Ubuntu"

    - name: install packages
      apt:
        name:
          - btrfs-compsize    # Check the compression ratio on btrfs
          - btrfs-heatmap     # Visualize how data is stored on disk
          - catimg            # Display images in terminal
          - clevis-dracut     # Decrypt Luks during boot with TPM
          - clevis-udisks2    # Decrypt Luks with TPM when inserting disk
          - davfs2            # DavFS for mounting Nextcloud, no need to sync everything
          - dconf-editor      # Change configuration under the hood of Gnome
          - dstat             # Stat system values in colors
          - duperemove        # Dedup btrfs
          - etckeeper         # Watch what happens in /etc
          - ffmpeg            # Transcode audio and video
          - file              # What file is this?
          - flac              # Lossless audio
          - flatpak           # Here be GUI software, don't use snap
          - git               # Version control <3
          - gnome-tweaks      # Customize Gnome
          - hugo              # Static blog generator
          - lame              # Encode mp3
          - lftp              # FTP isn't dead
          - libpam-u2f        # U2F token 2 factor in PAM
          - ltrace            # Trace library calls
          - mediainfo         # Used by AAX
          - ncdu              # Interactive du
          - nmap              # Scan network ports
          - offlineimap       # Make local backup of IMAP
          - pamu2fcfg         # Set up U2F token
          - pcscd             # Windows SCard interface
          - pv                # How fast do we transfer
          - python3-pygments  # Syntax highlighting in Hugo
          - python3-qrcode    # Generate QR-codes in terminal with qr
          - python3-venv      # Use python virtual environmens
          - rsync             # Syncing files, syncing life
          - scdaemon          # Smart card daemon
          - strace            # String trace processes
          - syncthing         # To sync stuff
          - tlp               # Save battery power on laptops
          - tmux              # <3
          - u2f-host          # Commandline U2F operations
          - ufw               # Uncomplicated firewall
          - vagrant           # Automate VMs
          - vagrant-sshfs     # Better to do this, than using buggy nfs
          - vim               # <3
          - virt-manager      # Graphical interface to Libvirt
          - whois             # A must
          - wireguard-tools   # Wireguard VPN
          - yamllint          # YAML files need to be linted too
          - yubikey-personalization-gui  # Yubico configuration
          - yubioath-desktop  # The Yubico Authenticator
          - zmap              # Map internet
          - zram-tools        # Zram swap

    - name: increase user watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: "2097152"

    - name: disable pstate and bling
      ini_file:
        path: /etc/default/grub
        no_extra_spaces: true
        section: null
        option: "{{ item.o }}"
        value: "{{ item.v }}"
        create: true
        mode: 0644
      loop:
        - o: GRUB_CMDLINE_LINUX_DEFAULT
          v: "splash intel_pstate=disable"
        - o: GRUB_TIMEOUT
          v: 3
      register: grub_conf

    - name: update grub
      command: update-grub
      when: grub_conf is changed

    - name: configure tlp
      ini_file:
        path: /etc/tlp.d/99-custom.conf
        section: null
        option: '{{ item.o }}'
        value: '{{ item.v  }}'
        no_extra_spaces: true
        mode: 0644
      loop:
        - o: CPU_ENERGY_PERF_POLICY_ON_AC
          v: balance_performance
        - o: CPU_ENERGY_PERF_POLICY_ON_BAT
          v: balance_power
        - o: CPU_BOOST_ON_AC
          v: '1'
        - o: CPU_BOOST_ON_BAT
          v: '0'
        - o: CPU_HWP_DYN_BOOST_ON_AC
          v: '1'
        - o: CPU_HWP_DYN_BOOST_ON_BAT
          v: '0'
        - o: CPU_SCALING_GOVERNOR_ON_AC
          v: schedutil
        - o: CPU_SCALING_GOVERNOR_ON_BAT
          v: schedutil
        - o: RADEON_DPM_STATE_ON_AC
          v: performance
        - o: RADEON_DPM_STATE_ON_BAT
          v: battery
        - o: RADEON_POWER_PROFILE_ON_AC
          v: auto
        - o: RADEON_POWER_PROFILE_ON_BAT
          v: low
        - o: RADEON_DPM_PERF_LEVEL_ON_AC
          v: auto
        - o: RADEON_DPM_PERF_LEVEL_ON_BAT
          v: low
        - o: STOP_CHARGE_THRESH_BAT0
          v: '1'
      register: tlp_config
      tags:
        - tlp

    - name: zstd zram swap
      ini_file:
        path: /etc/default/zramswap
        no_extra_spaces: true
        section: null
        option: "{{ item.o }}"
        value: "{{ item.v }}"
        create: true
        mode: 0644
      loop:
        - o: ALGO
          v: lz4
        - o: PERCENT
          v: 50


    - name: disable the unsecure firewire-dma
      copy:
        dest: /etc/modprobe.d/blacklist-dma.conf
        mode: 0644
        content: |
          blacklist firewire-core
          blacklist thunderbolt

#    - name: pam yubikey
#      lineinfile:
#        path: '{{ item }}'
#        insertafter: pam_faildelay.so
#        firstmatch: true
#        line: auth sufficient pam_u2f.so cue
#      loop:
#        # - /etc/pam.d/password-auth
#        - /etc/pam.d/system-auth
#      tags:
#        - pam

    - name: enable services
      service:
        name: '{{ item }}'
        enabled: true
        state: started
      loop:
        - pcscd.service       # Smart card daemon
        - ufw                 # Simpler firewall, Ubuntus default
        - tlp                 # Enable powersavings on battery
        - zramswap            # Enable zram swap

    - name: disable services
      service:
        name: '{{ item }}'
        enabled: false
        masked: true
        state: stopped
      loop:
        - power-profiles-daemon # gnome integrated power profiles daemon

    - name: deny incomming, and don't bother to log
      ufw:
        policy: deny
        direction: incoming
        log: false
        state: enabled

    - name: fix for slow wifi
      copy:
        dest: /etc/systemd/network/10-intel-wifi.link
        mode: 0644
        content: |
          [Match]
          Driver=iwlwifi

          [Link]
          TCPSegmentationOffload=false
          NamePolicy=keep kernel database onboard slot path

    - name: flatpak remote flathub
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: flatpak remote fedora
      flatpak_remote:
        name: fedora
        state: present
        flatpakrepo_url: oci+https://registry.fedoraproject.org

    - name: install flatpaks from flathub
      flatpak:
        name: '{{ item }}'
        remote: flathub
      loop:
        - com.belmoussaoui.Decoder
        - com.calibre_ebook.calibre
        - com.github.micahflee.torbrowser-launcher
        - com.github.phase1geo.minder
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.nextcloud.desktopclient.nextcloud
        - fr.handbrake.ghb
        - io.github.quodlibet.ExFalso
        - net.supertuxkart.SuperTuxKart
        - org.audacityteam.Audacity
        - org.chromium.Chromium
        - org.duckstation.DuckStation
        - org.gabmus.whatip
        - org.gimp.GIMP
        - org.gnome.Calendar
        - org.gnome.Epiphany
        - org.gnome.Evince
        - org.gnome.Extensions
        - org.gnome.FileRoller
        - org.gnome.Maps
        - org.gnome.Shotwell
        - org.gnome.TextEditor
        - org.gnome.Todo
        - org.gnome.Weather
        - org.gnome.clocks
        - org.gnome.gitlab.somas.Apostrophe
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
        - org.remmina.Remmina
        - org.signal.Signal
        - org.supertuxproject.SuperTux
        - org.videolan.VLC

    # - name: install flatpaks from fedora
    #   flatpak:
    #     name: '{{ item }}'
    #     remote: fedora
    #   loop:

