# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure ubuntu desktop
  hosts: localhost

  tasks:
    - name: run only on ubuntu
      become: true
      assert:
        that: ansible_distribution == "Ubuntu"

    - name: install packages
      become: true
      apt:
        name:
          - btrfs-compsize    # Check the compression ratio on btrfs
          - btrfs-heatmap     # Visualize how data is stored on disk
          - catimg            # Display images in terminal
          - davfs2            # DavFS for mounting Nextcloud, no need to sync everything
          - dconf-editor      # Change configuration under the hood of Gnome
          - dstat             # Stat system values in colors
          - duperemove        # Dedup btrfs
          - etckeeper         # Watch what happens in /etc
          - ffmpeg            # Transcode audio and video
          - file              # What file is this?
          - flac              # Lossless audio
          - flatpak           # Here be GUI software, don't use snap
          - git               # Version control <3
          - gnome-tweaks      # Customize Gnome
          - hugo              # Static blog generator
          - lame              # Encode mp3
          - lftp              # FTP isn't dead
          - libpam-u2f        # U2F token 2 factor in PAM
          - ltrace            # Trace library calls
          - mediainfo         # Used by AAX
          - ncdu              # Interactive du
          - nmap              # Scan network ports
          - offlineimap       # Make local backup of IMAP
          - pamu2fcfg         # Set up U2F token
          - pcscd             # Windows SCard interface
          - pv                # How fast do we transfer
          - python3-pygments  # Syntax highlighting in Hugo
          - python3-qrcode    # Generate QR-codes in terminal with qr
          - python3-venv      # Use python virtual environmens
          - rsync             # Syncing files, syncing life
          - scdaemon          # Smart card daemon
          - strace            # String trace processes
          - syncthing         # To sync stuff
          - tmux              # <3
          - u2f-host          # Commandline U2F operations
          - ufw               # Uncomplicated firewall
          - vagrant           # Automate VMs
          - vagrant-sshfs     # Better to do this, than using buggy nfs
          - vim               # <3
          - virt-manager      # Graphical interface to Libvirt
          - whois             # A must
          - wireguard-tools   # Wireguard VPN
          - yamllint          # YAML files need to be linted too
          - yubikey-personalization-gui  # Yubico configuration
          - yubioath-desktop  # The Yubico Authenticator
          - zmap              # Map internet

    - name: increase user watches
      become: true
      sysctl:
        name: fs.inotify.max_user_watches
        value: "2097152"

    - name: fix for slow wifi
      become: true
      copy:
        dest: /etc/systemd/network/10-intel-wifi.link
        mode: 0644
        content: |
          [Match]
          Driver=iwlwifi

          [Link]
          TCPSegmentationOffload=false
          NamePolicy=keep kernel database onboard slot path

    - name: Flatpak remote flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        method: user
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Flatpak remote fedora
      community.general.flatpak_remote:
        name: fedora
        state: present
        method: user
        flatpakrepo_url: oci+https://registry.fedoraproject.org

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name: '{{ item }}'
        remote: flathub
        method: user
      loop:
        - com.calibre_ebook.calibre
        - com.github.micahflee.torbrowser-launcher
        - com.github.phase1geo.minder
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - fr.handbrake.ghb
        - io.github.quodlibet.ExFalso
        - org.audacityteam.Audacity
        - org.chromium.Chromium
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
        - org.signal.Signal

    - name: Install flatpaks from fedora
      community.general.flatpak:
        name: '{{ item }}'
        remote: fedora
        method: user
      loop: [ ]

