# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure debian desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on debain distros
      assert:
        that: ansible_os_family == "Debian"

    - name: remove packages that's installed as flatpaks
      apt:
        state: absent
        name:
          - shotwell              # Remove the the Photo organizer

    - name: install packages
      apt:
        name:
            # - arm-image-installer  # Install arm images, ie. fedora arm on a SD-card
            # - duply             # Vrapper for Duplicity backup
            # - iucode-tool       # Intel microcode tool
            # - libdvdcss         # Play your old DVDs on Linux
            # - libgnome-keyring  # Save passwords in Nextcloud, missing dep.
            # - libmp4v2          # Need it, realy need it
            # - marker            # A good GTK markdown editor
            # - network-manager-openvpn-gnome  # Connect to OpenVPN server
            # - rkhunter          # Root kit hunter, just the basics
          - syncthing         # To sync stuff
            # - vim-syntastic     # <3
            # - yubikey-personalization-gui  # Yubico configuration
            # - yubioath-desktop      # The Yubico Authenticator
          - ansible-core          # Automate everything
          - ansible-lint          # Lint everything
          - btrfs-compsize        # Check the compression ratio on btrfs
          - btrfs-heatmap         # Visualize how data is stored on disk
          - catimg                # Display images in terminal
          - clevis                # Automatic decrypt disk
          - clevis-initramfs
          - clevis-tpm2
          - clevis-udisks2
          - curl                  # Fetch stuff from the Internet
          - davfs2                # DavFS for mounting Nextcloud, no need to sync everything
          - dconf-editor          # Edit desktop configuration
          - dstat                 # Stat system values in colors
          - duperemove            # Dedup btrfs
          - etckeeper             # Watch what happens in /etc
          - ffmpeg                # Transcode audio and video
          - flac                  # Lossless audio
          - flatpak               # Flatpak for extra graphical programs
          - gedit-plugins         # Extra plugins for gedit
          - git                   # Version control <3
          - gnome-backgrounds     # More backgrounds
          - gnome-software-plugin-flatpak  # Integrate flatpak with gnome-software
          - gnome-tweaks          # Customize Gnome
          - gnupg-pkcs11-scd      # Smart card functionality for SSH keys on Yubikey
          - haveged               # More random data from CPU flutter
          - hugo                  # Static blog generator
          - lame                  # Encode mp3
          - lftp                  # FTP isn't dead
          - libpam-u2f            # U2F token 2 factor in PAM
          - ltrace                # Trace library calls
          - menulibre             # Edit Gnome menu items
          - mtr                   # Better traceroute
          - nmap                  # Scan network ports
          - npm                   # Needed by vim-lsp
          - offlineimap           # Make local backup of IMAP
          - pamu2fcfg             # Set up U2F token
          - pcscd                 # Smart card daemon
          - pv                    # How fast do we transfer
          - python3-pip           # Yes, need to install python packages
          - python3-pygments      # Syntax highlighting in Hugo
          - python3-qrcode        # Generate QR-codes in terminal with qr
          - resolvconf            # Needed for wireguard DNS configuration
          - rsync                 # Syncing files, syncing life
          - screenfetch           # Screenshot information tool
          - strace                # String trace processes
          - sysfsutils            # Control /sys
          - tlp                   # Save battery power on laptops
          - tmux                  # <3
          - tree                  # Show dirs as tree structure
          - u2f-host              # Commandline U2F operations
          - ufw                   # Uncomplicated firewall
          - vim-nox               # <3
          - virt-manager          # Graphical interface to Libvirt
          - whois                 # A must
          - wireguard-tools       # Wireguard VPN
          - yamllint              # YAML files need to be linted too
          - zmap                  # Map internet
          - zram-tools            # Zram swap

    - name: increase user watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: "2097152"

    - name: configure 50% of mem to zramswap with zstd compression
      ini_file:
        path: /etc/default/zramswap
        section: null
        option: '{{ item.o }}'
        value: '{{ item.v  }}'
        no_extra_spaces: true
        mode: 0644
      loop:
        - o: ALGO
          v: zstd
        - o: PERCENT
          v: 50

    - name: configure tlp
      ini_file:
        path: /etc/tlp.d/99-custom.conf
        section: null
        option: '{{ item.o }}'
        value: '{{ item.v  }}'
        no_extra_spaces: true
        mode: 0644
      loop:
        - o: CPU_ENERGY_PERF_POLICY_ON_AC
          v: balance_performance
        - o: CPU_ENERGY_PERF_POLICY_ON_BAT
          v: balance_power
        - o: CPU_BOOST_ON_AC
          v: '1'
        - o: CPU_BOOST_ON_BAT
          v: '0'
        - o: CPU_HWP_DYN_BOOST_ON_AC
          v: '1'
        - o: CPU_HWP_DYN_BOOST_ON_BAT
          v: '0'
        - o: CPU_SCALING_GOVERNOR_ON_AC
          v: schedutil
        - o: CPU_SCALING_GOVERNOR_ON_BAT
          v: schedutil
        - o: RADEON_DPM_STATE_ON_AC
          v: performance
        - o: RADEON_DPM_STATE_ON_BAT
          v: battery
        - o: RADEON_POWER_PROFILE_ON_AC
          v: auto
        - o: RADEON_POWER_PROFILE_ON_BAT
          v: low
        - o: RADEON_DPM_PERF_LEVEL_ON_AC
          v: auto
        - o: RADEON_DPM_PERF_LEVEL_ON_BAT
          v: low
        - o: STOP_CHARGE_THRESH_BAT0
          v: '1'
      register: tlp_config
      tags:
        - tlp

    - name: disable the unsecure firewire-dma
      copy:
        dest: /etc/modprobe.d/blacklist-dma.conf
        mode: 0644
        content: |
          blacklist firewire-core
          blacklist thunderbolt

    - name: fix rotation on ideapad d330
      copy:
        dest: /etc/udev/hwdb.d/61-sensor-local.hwdb
        mode: 0644
        content: |
          # IdeaPad D330
          sensor:modalias:acpi:BOSC0200*:dmi:*:svnLENOVO:*:pvrLenovoideapadD330*
              ACCEL_MOUNT_MATRIX=0, 1, 0; -1, 0, 0; 0, 0, 1
      register: hwdb_update

    - name: update hwdb
      command: systemd-hwdb update
      when: hwdb_update is changed

        # - name: pam yubikey
        #   lineinfile:
        #     path: '{{ item }}'
        #     insertafter: pam_faildelay.so
        #     firstmatch: true
        #     line: auth sufficient pam_u2f.so cue
        #   loop:
        #     # - /etc/pam.d/password-auth
        #     - /etc/pam.d/system-auth
        #   tags:
        #     - pam

    - name: enable services
      service:
        name: '{{ item }}'
        enabled: true
        state: started
      loop:
        - pcscd               # Smart card daemon
        - ufw                 # Simpler firewall, Ubuntus default
        - zramswap            # Use only ram based swap
        - tlp                 # Enable powersavings on battery

    - name: deny incomming, and don't bother to log
      ufw:
        policy: deny
        direction: incoming
        log: false
        state: enabled

    - name: fix for slow wifi
      copy:
        dest: /etc/systemd/network/10-intel-wifi.link
        mode: 0644
        content: |
          [Match]
          Driver=iwlwifi

          [Link]
          TCPSegmentationOffload=false
          NamePolicy=keep kernel database onboard slot path

    - name: flatpak remote flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: flatpak remote fedora
      community.general.flatpak_remote:
        name: fedora
        state: present
        flatpakrepo_url: oci+https://registry.fedoraproject.org

    - name: install flatpaks from flathub
      community.general.flatpak:
        name: '{{ item }}'
        remote: flathub
      loop:
        - com.belmoussaoui.Decoder
        - com.calibre_ebook.calibre
        - com.github.micahflee.torbrowser-launcher
        - com.github.phase1geo.minder
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.nextcloud.desktopclient.nextcloud
        - fr.handbrake.ghb
        - io.github.quodlibet.ExFalso
        - net.supertuxkart.SuperTuxKart
        - org.audacityteam.Audacity
        - org.chromium.Chromium
        - org.duckstation.DuckStation
        - org.gabmus.whatip
        - org.gimp.GIMP
        - org.gnome.Dictionary
        - org.gnome.Epiphany
        - org.gnome.Evince
        - org.gnome.Extensions
        - org.gnome.FileRoller
        - org.gnome.Maps
        - org.gnome.Shotwell
        - org.gnome.TextEditor
        - org.gnome.Todo
        - org.gnome.gitlab.somas.Apostrophe
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
        - org.remmina.Remmina
        - org.signal.Signal
        - org.supertuxproject.SuperTux
        - org.videolan.VLC

    - name: install flatpaks from fedora
      community.general.flatpak:
        name: '{{ item }}'
        remote: fedora
      loop: []

