# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: Configure debian desktop
  hosts: localhost
  become: true

  tasks:
    - name: Run only on debain distros
      ansible.builtin.assert:
        that: ansible_os_family == "Debian"

    - name: add repo key media repo
      ansible.builtin.apt:
        force: true
        deb: https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2024.9.1_all.deb
        
    - name: add media repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/dmo.sources
        mode: "0644"
        content: |
          Types: deb
          URIs: https://www.deb-multimedia.org
          Suites: {{ ansible_distribution_release }}
          Components: main non-free
          Signed-By: /usr/share/keyrings/deb-multimedia-keyring.pgp
          Enabled: yes

    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - adwaita-qt
          - adwaita-qt6
          - btrfs-compsize        # Check the compression ratio on btrfs
          - btrfs-heatmap         # Visualize how data is stored on disk
          - catimg                # Display images in terminal
          - curl                  # Fetch stuff from the Internet
          - dstat                 # Stat system values in colors
          - duperemove            # Dedup btrfs
          - etckeeper             # Watch what happens in /etc
          - ffmpeg                # Transcode audio and video
          - flac                  # Lossless audio
          - git                   # Version control <3
          - gnome-shell-extension-appindicator  # Legacy app indicator
          - gnome-shell-extension-caffeine  # Don't sleep on fullscreen
          - gnome-software-plugin-flatpak  # Integrate flatpak with gnome-software
          - gnupg-pkcs11-scd      # Smart card functionality for SSH keys on Yubikey
          - lame                  # Encode mp3
          - libdvdcss         # Play your old DVDs on Linux
          - libmp4v2-2        # Need it, realy need it
          - libpam-u2f            # U2F token 2 factor in PAM
          - ltrace                # Trace library calls
          - mp4v2-utils
          - mtr                   # Better traceroute
          - nautilus-nextcloud    # Nextcloud integration into nautilus
          - ncdu                  # Visual terminal 'du -h'
          - nmap                  # Scan network ports
          - offlineimap           # Make local backup of IMAP
          - pamu2fcfg             # Set up U2F token
          - pcscd                 # Smart card daemon
          - pipx                  # Yes, need to install python programs
          - podman                # Yep! Containers, containers...
          - pv                    # How fast do we transfer
          - python3-pip           # Yes, need to install python packages
          - python3-pygments      # Syntax highlighting in Hugo
          - python3-qrcode        # Generate QR-codes in terminal with qr
          - qgnomeplatform-qt5    # Better Qt integration
          - qgnomeplatform-qt6
          - qt5ct
          - qt6-wayland
          - qt6ct
          - qtwayland5
          - rsync                 # Syncing files, syncing life
          - strace                # String trace processes
          - sysfsutils            # Control /sys
          - systemd-zram-generator # Use the new ram zswap
          - tmux                  # <3
          - tree                  # Show dirs as tree structure
          - u2f-host              # Commandline U2F operations
          - ufw                   # Uncomplicated firewall
          - virt-manager          # Graphical interface to Libvirt
          - whois                 # A must
          - wireguard-tools       # Wireguard VPN
          - yamllint              # YAML files need to be linted too
          - zmap                  # Map internet

    - name: Increase user watches
      ansible.builtin.sysctl:
        name: fs.inotify.max_user_watches
        value: "2097152"

    # - name: Fix rotation on ideapad d330
    #   become: true
    #   ansible.builtin.copy:
    #     dest: /etc/udev/hwdb.d/61-sensor-local.hwdb
    #     mode: 0644
    #     content: |
    #       # IdeaPad D330
    #       sensor:modalias:acpi:BOSC0200*:dmi:*:svnLENOVO:*:pvrLenovoideapadD330*
    #           ACCEL_MOUNT_MATRIX=0, 1, 0; -1, 0, 0; 0, 0, 1
    #   notify: handler_hwdb_update


    # - name: pam yubikey
    #   lineinfile:
    #     path: '{{ item }}'
    #     insertafter: pam_faildelay.so
    #     firstmatch: true
    #     line: auth sufficient pam_u2f.so cue
    #   loop:
    #     # - /etc/pam.d/password-auth
    #     - /etc/pam.d/system-auth
    #   tags:
    #     - pam

    - name: Enable services
      ansible.builtin.service:
        name: '{{ item }}'
        enabled: true
        state: started
      loop:
        - ufw                 # Simpler firewall, Ubuntus default

    - name: Deny incomming, and don't bother to log
      become: true
      ansible.builtin.ufw:
        policy: deny
        direction: incoming
        log: false
        state: enabled

    # - name: Fix for slow wifi
    #   ansible.builtin.copy:
    #     dest: /etc/systemd/network/10-intel-wifi.link
    #     mode: 0644
    #     content: |
    #       [Match]
    #       Driver=iwlwifi

    #       [Link]
    #       TCPSegmentationOffload=false
    #       NamePolicy=keep kernel database onboard slot path

    - name: Flatpak remote flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        method: system
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Flatpak remote fedora
      community.general.flatpak_remote:
        name: fedora
        state: present
        method: system
        flatpakrepo_url: oci+https://registry.fedoraproject.org

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name: '{{ item }}'
        remote: flathub
        method: system
      loop:
        - com.calibre_ebook.calibre
        - com.github.micahflee.torbrowser-launcher
        - com.github.tchx84.Flatseal
        - fr.handbrake.ghb
        - io.github.quodlibet.ExFalso
        - org.audacityteam.Audacity
        - org.gimp.GIMP
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - org.signal.Signal
        - org.upscayl.Upscayl
        # - com.github.phase1geo.minder
        # - com.mattjakeman.ExtensionManager
        # - net.supertuxkart.SuperTuxKart
        # - com.belmoussaoui.Decoder
        # - com.nextcloud.desktopclient.nextcloud
        # - org.chromium.Chromium
        # - org.gabmus.whatip
        # - org.gnome.Dictionary
        # - org.gnome.Epiphany
        # - org.gnome.Evince
        # - org.gnome.Evolution
        # - org.gnome.Extensions
        # - org.gnome.FileRoller
        # - org.gnome.gitlab.somas.Apostrophe
        # - org.gnome.Maps
        # - org.gnome.Shotwell
        # - org.gnome.TextEditor
        # - org.gnome.Todo
        # - org.remmina.Remmina
        # - org.supertuxproject.SuperTux
        # - org.videolan.VLC

    - name: Install flatpaks from fedora
      community.general.flatpak:
        name: '{{ item }}'
        remote: fedora
        method: user
      loop: [ ]

  # handlers:
  #   - name: Update hwdb
  #     ansible.builtin.command: systemd-hwdb update
  #     listen: handler_hwdb_update
  #     become: true
