# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure fedora desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on fedora
      ansible.builtin.assert:
        that: ansible_distribution == "Debian"

    - name: add repo key media repo
      ansible.builtin.apt:
        force: true
        deb: https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2024.9.1_all.deb

    - name: add media repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/dmo.sources
        mode: "0644"
        content: |
          Types: deb
          URIs: https://www.deb-multimedia.org
          Suites: {{ ansible_distribution_release }}
          Components: main non-free
          Signed-By: /usr/share/keyrings/deb-multimedia-keyring.pgp
          Enabled: yes

    - name: add media repo
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/pin-media.pref
        mode: "0644"
        content: |
          Package: *
          Pin: origin "www.deb-multimedia.org"
          Pin-Priority: 100

    - name: install packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - dstat             # Stat system values in colors
          - duperemove        # Dedup btrfs
          - etckeeper         # Watch what happens in /etc
          - exfalso           # Edit MP3/MP4 metadata
          - ffmpeg            # Transcode audio and video
          - file              # What file is this?
          - flac              # Lossless audio
          - flatpak           # Get software from flathub
          - git               # Version control <3
          - lame              # Encode mp3
          - lftp              # FTP isn't dead
          - mediainfo         # Manipulate mediainfo on mediafiles
          - mp4v2-utils       # For working with mp4 files
          - ncdu              # Interactive du
          - nmap              # Scan network ports
          - offlineimap       # Make local backup of IMAP
          - pv                # How fast do we transfer
          - python3-qrcode    # Generate QR-codes in terminal with qr
          - rsync             # Syncing files, syncing life
          - strace            # String trace processes
          - thunderbird       # Mail on chromebook in a sensible way
          - tmux              # <3
          - vim               # <3
          - zmap              # Map internet

    - name: flatpak remote flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        method: user
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      become: false

    - name: flatpak remote fedora
      community.general.flatpak_remote:
        name: fedora
        state: present
        method: user
        flatpakrepo_url: oci+https://registry.fedoraproject.org
      become: false

    - name: install flatpaks from flathub
      community.general.flatpak:
        name: '{{ item }}'
        remote: flathub
        method: user
      become: false
      loop:
        - com.calibre_ebook.calibre

    - name: install flatpaks from fedora
      community.general.flatpak:
        name: '{{ item }}'
        remote: fedora
        method: user
      become: false
      loop: []

