# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure fedora desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on fedora
      ansible.builtin.assert:
        that: ansible_distribution == "Debian"

    - name: add repo key media repo
      ansible.builtin.apt_key:
        id: A401FF99368FA1F98152DE755C808C2B65558117
        keyserver: keyring.debian.org
        keyring: /etc/apt/trusted.gpg.d/ansible.gpg

    - name: add media repo
      ansible.builtin.apt_repository:
        repo: deb http://www.deb-multimedia.org bullseye main
        filename: ansible
        state: present


    - name: install packages
      ansible.builtin.apt:
        name:
          - davfs2            # DavFS for mounting Nextcloud, no need to sync everything
          - dstat             # Stat system values in colors
          - duperemove        # Dedup btrfs
          - eb-multimedia-keyring # Keyring for debian media packages
          - etckeeper         # Watch what happens in /etc
          - ffmpeg            # Transcode audio and video
          - file              # What file is this?
          - flac              # Lossless audio
          - git               # Version control <3
          - hugo              # Static blog generator
          - lame              # Encode mp3
          - lftp              # FTP isn't dead
          - mediainfo         # Manipulate mediainfo on mediafiles
          - mediainfo         # Used by AAX
          - mp4v2-utils       # For working with mp4 files
          - ncdu              # Interactive du
          - nmap              # Scan network ports
          - offlineimap       # Make local backup of IMAP
          - pv                # How fast do we transfer
          - python3-pygments  # Syntax highlighting in Hugo
          - python3-qrcode    # Generate QR-codes in terminal with qr
          - rsync             # Syncing files, syncing life
          - strace            # String trace processes
          - tmux              # <3
          - vim               # <3
          - zmap              # Map internet

    - name: flatpak remote flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        method: user
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      become: false

    - name: flatpak remote fedora
      community.general.flatpak_remote:
        name: fedora
        state: present
        method: user
        flatpakrepo_url: oci+https://registry.fedoraproject.org
      become: false

    - name: install flatpaks from flathub
      community.general.flatpak:
        name: '{{ item }}'
        remote: flathub
        method: user
      become: false
      loop:
        - com.calibre_ebook.calibre
        - org.gnome.TextEditor

    - name: install flatpaks from fedora
      community.general.flatpak:
        name: '{{ item }}'
        remote: fedora
        method: user
      become: false
      loop: []

