# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure debian desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on debain distros
      assert:
        that: ansible_os_family == "Debian"

    - name: install packages
      apt:
        name:
            # - arm-image-installer  # Install arm images, ie. fedora arm on a SD-card
            # - bijiben           # Note taking
            # - duply             # Vrapper for Duplicity backup
            # - exfalso           # Edit tags on mp3s
            # - gnome-backgrounds-extras  # Favorite backgrounds
            # - gthumb            # Photo manager that works with remote folders
            # - iucode-tool       # Intel microcode tool
            # - libdvdcss         # Play your old DVDs on Linux
            # - libgnome-keyring  # Save passwords in Nextcloud, missing dep.
            # - libmp4v2          # Need it, realy need it
            # - libvirt-client    # Libvirts virsh
            # - marker            # A good GTK markdown editor
            # - powertop          # What is using my power
            # - python3-boto      # S3 library for Duplicity
            # - rkhunter          # Root kit hunter, just the basics
            # - seahorse          # GPG graphical interface
            # - syncthing         # To sync stuff
            # - tlp               # Save battery power on laptops
            # - vim-syntastic     # <3
          - ansible              # Automate everything
          - ansible-lint         # Lint everything
          - btrfs-compsize       # Check the compression ratio on btrfs
          - btrfs-heatmap        # Visualize how data is stored on disk
          - catimg               # Display images in terminal
          - curl                 # Fetch stuff from the Internet
          - davfs2               # DavFS for mounting Nextcloud, no need to sync everything
          - dconf-editor         # Edit desktop configuration
          - dstat                # Stat system values in colors
          - duperemove           # Dedup btrfs
          - etckeeper            # Watch what happens in /etc
          - ffmpeg               # Transcode audio and video
          - flac                 # Lossless audio
          - flatpak              # Flatpak for extra graphical programs
          - gedit-plugins        # Extra plugins for gedit
          - git                  # Version control <3
          - gnome-backgrounds    # More backgrounds
          - gnome-software-plugin-flatpak  # Integrate flatpak with gnome-software
          - gnome-tweaks         # Customize Gnome
          - gnupg-pkcs11-scd     # Smart card functionality for SSH keys on Yubikey
          - haveged              # More random data from CPU flutter
          - hugo                 # Static blog generator
          - lame                 # Encode mp3
          - lftp                 # FTP isn't dead
          - libpam-u2f           # U2F token 2 factor in PAM
          - ltrace               # Trace library calls
          - nmap                 # Scan network ports
          - npm                  # Needed by vim-lsp
          - offlineimap          # Make local backup of IMAP
          - pamu2fcfg            # Set up U2F token
          - pcscd                # Smart card daemon
          - pv                   # How fast do we transfer
          - python3-pip          # Yes, need to install python packages
          - python3-pygments     # Syntax highlighting in Hugo
          - python3-qrcode       # Generate QR-codes in terminal with qr
          - rsync                # Syncing files, syncing life
          - strace               # String trace processes
          - sysfsutils           # Control /sys
          - tmux                 # <3
          - u2f-host             # Commandline U2F operations
          - ufw                  # Uncomplicated firewall
          - vagrant              # Automate testing with full OSes
          - vagrant-sshfs        # Mount filesystem into vagrant via SSH
          - vim-nox              # <3
          - virt-manager         # Graphical interface to Libvirt
          - virtualbox           # Desktop virtualization
            # - virtualbox-ext-pack  # Allow USB2.0/3.0
          - whois                # A must
          - yamllint             # YAML files need to be linted too
          - yubikey-personalization-gui  # Yubico configuration
          - yubioath-desktop     # The Yubico Authenticator
          - zmap                 # Map internet
          - zram-tools           # Zram swap

    - name: pin gnome-shell from unstable
      copy:
        dest: /etc/apt/preferences.d/gnome
        mode: 0664
        content: |
          Package: *
          Pin: release a=unstable
          Pin-Priority: 50

          Package: gnome-session
          Pin: release a=unstable
          Pin-Priority: 1000

          Package: gnome-backgrounds
          Pin: release a=unstable
          Pin-Priority: 1000

          Package: gnome-applets
          Pin: release a=unstable
          Pin-Priority: 1000

          Package: gnome-control-center
          Pin: release a=unstable
          Pin-Priority: 1000

          Package: mutter
          Pin: release a=unstable
          Pin-Priority: 1000

          Package: gjs
          Pin: release a=unstable
          Pin-Priority: 1000

          Package: gnome-tweaks
          Pin: release a=unstable
          Pin-Priority: 1000

    - name: install gnome-shell from unstable
      apt:
        default_release: unstable
        name:
          - gjs
          - gnome-applets
          - gnome-backgrounds
          - gnome-control-center
          - gnome-session
          - gnome-shell
          - gnome-tweaks
          - mutter

    - name: add debian unstable repository
      apt_repository:
        repo: '{{ item }}'
        filename: unstable
      loop:
        - deb http://deb.debian.org/debian unstable main contrib non-free
        - deb-src http://deb.debian.org/debian unstable main contrib non-free

    - name: increase user watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: "2097152"

    # In grub intel_pstate=disable

    - name: configure tlp
      ini_file:
        path: /etc/tlp.d/99-custom.conf
        section: null
        option: '{{ item.o }}'
        value: '{{ item.v  }}'
        no_extra_spaces: true
        mode: 0644
      loop:
        - o: CPU_ENERGY_PERF_POLICY_ON_AC
          v: balance_performance
        - o: CPU_ENERGY_PERF_POLICY_ON_BAT
          v: balance_power
        - o: CPU_BOOST_ON_AC
          v: '1'
        - o: CPU_BOOST_ON_BAT
          v: '0'
        - o: CPU_HWP_DYN_BOOST_ON_AC
          v: '1'
        - o: CPU_HWP_DYN_BOOST_ON_BAT
          v: '0'
        - o: CPU_SCALING_GOVERNOR_ON_AC
          v: schedutil
        - o: CPU_SCALING_GOVERNOR_ON_BAT
          v: schedutil
        - o: RADEON_DPM_STATE_ON_AC
          v: performance
        - o: RADEON_DPM_STATE_ON_BAT
          v: battery
        - o: RADEON_POWER_PROFILE_ON_AC
          v: auto
        - o: RADEON_POWER_PROFILE_ON_BAT
          v: low
        - o: RADEON_DPM_PERF_LEVEL_ON_AC
          v: auto
        - o: RADEON_DPM_PERF_LEVEL_ON_BAT
          v: low
        - o: STOP_CHARGE_THRESH_BAT0
          v: '1'
      register: tlp_config
      tags:
        - tlp

    - name: zstd zram swap
      ini_file:
        path: /etc/systemd/zram-generator.conf
        section: zram0
        option: compression-algorithm
        value: zstd
        create: true
        mode: 0644

    - name: disable the unsecure firewire-dma
      copy:
        dest: /etc/modprobe.d/blacklist-dma.conf
        mode: 0644
        content: |
          blacklist firewire-core
          blacklist thunderbolt

    - name: fix rotation on ideapad d330
      copy:
        dest: /etc/udev/hwdb.d/61-sensor-local.hwdb
        mode: 0644
        content: |
          # IdeaPad D330
          sensor:modalias:acpi:BOSC0200*:dmi:*:svnLENOVO:*:pvrLenovoideapadD330*
              ACCEL_MOUNT_MATRIX=0, 1, 0; -1, 0, 0; 0, 0, 1
      register: hwdb_update

    - name: update hwdb
      command: systemd-hwdb update
      when: hwdb_update is changed

        # - name: pam yubikey
        #   lineinfile:
        #     path: '{{ item }}'
        #     insertafter: pam_faildelay.so
        #     firstmatch: true
        #     line: auth sufficient pam_u2f.so cue
        #   loop:
        #     # - /etc/pam.d/password-auth
        #     - /etc/pam.d/system-auth
        #   tags:
        #     - pam

    - name: enable services
      service:
        name: '{{ item }}'
        enabled: true
        state: started
      loop:
        - pcscd               # Smart card daemon
        - ufw                 # Simpler firewall, Ubuntus default
        - zramswap            # Use only ram based swap
          # - tlp                 # Enable powersavings on battery

    - name: deny incomming, and don't bother to log
      ufw:
        policy: deny
        direction: incoming
        log: false
        state: enabled

    - name: fix for slow wifi
      copy:
        dest: /etc/systemd/network/10-intel-wifi.link
        mode: 0644
        content: |
          [Match]
          Driver=iwlwifi

          [Link]
          TCPSegmentationOffload=false
          NamePolicy=keep kernel database onboard slot path

    - name: flatpak remote flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: flatpak remote fedora
      community.general.flatpak_remote:
        name: fedora
        state: present
        flatpakrepo_url: oci+https://registry.fedoraproject.org

    - name: install flatpaks from flathub
      community.general.flatpak:
        name: '{{ item }}'
        remote: flathub
      loop:
        - com.calibre_ebook.calibre
        - com.github.tchx84.Flatseal
        - com.nextcloud.desktopclient.nextcloud
        - io.github.quodlibet.ExFalso
        - org.chromium.Chromium
        - org.gimp.GIMP
        - org.gnome.Cheese
        - org.gnome.Dictionary
        - org.gnome.Evolution
        - org.gnome.Extensions
        - org.gnome.Maps
        - org.gnome.Shotwell
        - org.gnome.Totem
        - org.keepassxc.KeePassXC
        - org.mozilla.firefox
        - org.remmina.Remmina
        - org.videolan.VLC

    - name: install flatpaks from fedora
      community.general.flatpak:
        name: '{{ item }}'
        remote: fedora
      loop:
        - org.audacityteam.Audacity
