---
- name: common configuration for k3s nodes
  hosts:
    - k3s_master
    - k3s_agents
  become: true

  tasks:
    - name: set variables for all plays
      set_fact:
        k3s_master: '{{ groups["k3s_master"] | map("extract", hostvars, "node_ip") | list }}'
        k3s_agents: '{{ groups["k3s_agents"] | map("extract", hostvars, "node_ip") | list }}'
        k3s_version: '{{ k3s_version | default("v1.21.4+k3s1") }}'
        k9s_version: '{{ k9s_version | default("v0.24.15") }}'

    - name: install python-apt
      apt:
        name: python3-apt
      check_mode: false
      when: ansible_check_mode|bool

    - name: install packages
      apt:
        name:
          - unattended-upgrades     # auto-upgrade packages
          - wireguard               # wireguard for communication between k3s nodes
        update_cache: true

    ## ufw

    - name: install ufw
      package:
        name: ufw

    - name: enable and start ufw
      systemd:
        name: ufw
        enabled: true
        state: started

    - name: ufw allow ssh
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: ufw allow wireguard
      ufw:
        rule: allow
        port: '51820'
        proto: udp

    # - name: allow internal kubernetes communication
    #   ufw:
    #     rule: allow
    #     from: 10.42.0.0/16
    #     to: 10.42.0.0/16

    - name: ufw allow kubelet metrics
      ufw:
        rule: allow
        port: '10250'
        proto: tcp
        from: '{{ item }}'
      loop: '{{ k3s_master + k3s_agents }}'

    - name: ufw allow kubernetes api
      ufw:
        rule: allow
        port: '6443'
        proto: tcp
        from: '{{ item }}'
      loop: '{{ k3s_master + k3s_agents + [ "10.42.0.0/16" ] }}'
      when: inventory_hostname in groups["k3s_master"]

    - name: ufw allow etcd between masters
      ufw:
        rule: allow
        port: '2379:2380'
        proto: tcp
        from: '{{ item }}'
      loop: '{{ k3s_master }}'
      when: inventory_hostname in groups["k3s_master"]

    - name: allow kubernetes and pods to connect to systemd-resolv
      ufw:
        rule: allow
        port: '5355'
        from_ip: fe80::/64

    - name: allow forwarding to pods
      ini_file:
        path: /etc/default/ufw
        section: null
        option: DEFAULT_FORWARD_POLICY
        value: '"ACCEPT"'
        no_extra_spaces: true
        mode: 0644
      register: ufw_defaults

    - name: restart ufw on config change
      systemd:
        name: ufw
        state: restarted
      when: ufw_defaults is changed

    - name: enable ufw and set policy
      ufw:
        policy: reject
        state: enabled

    - name: remove swapfile from /etc/fstab
      mount:
        name: '{{ item }}'
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: get k3s install script from stable branch
      get_url:
        url: https://raw.githubusercontent.com/k3s-io/k3s/release-1.21/install.sh
        checksum: sha256:3a053a6acb6d348b8dc15c4c3d0eb78ff05e77021dbf30a537c7dd6574f2e84c
        dest: /root/install.sh
        mode: 0755

###############################################################################

- name: configure k3s master nodes
  hosts: k3s_master
  become: true
  vars:
    architecture_map:
      aarch64: arm64
      armv7l: arm
      x86_64: x86_64

  tasks:
    - name: ufw allow nfs
      ufw:
        rule: allow
        port: '{{ item.0 | string }}'
        from: '{{ item.1 }}'
      loop: '{{ [111,2049,20048] | product(k3s_master + k3s_agents) | list }}'
      when: nfs_ip is not defined

    - name: install nfs for serving storage to the cluster
      apt:
        name: nfs-kernel-server
      when: nfs_ip is not defined

    # https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
    - name: prepare space for nfs-subdir-external-provisioner and general volume to all nodes
      file:
        path: /nfs4/{{ item }}
        state: directory
        mode: a=rwxt
      loop:
        - automatic-pvcs
        - srv
      when: nfs_ip is not defined

    - name: share /nfs4 to the kubernetes cluster, so other nodes can start containers
      lineinfile:
        path: /etc/exports
        line: /nfs4 {{ item }}(rw,fsid=0,async,no_subtree_check,no_auth_nlm,insecure,no_root_squash)
        mode: 0644
        create: true
      loop: '{{ k3s_master + k3s_agents }}'
      register: etc_exportfs
      when: nfs_ip is not defined

    - name: export filesystems through nfs
      command: exportfs -r
      when:
        - etc_exportfs is changed
        - nfs_ip is not defined

    - name: install nfs client
      apt:
        name: nfs-client

    - name: mount nfs shared volume on srv
      mount:
        path: /srv
        src: '{{ nfs_ip | default( node_ip ) }}:/srv'
        opts: tcp
        state: mounted
        fstype: nfs4

    - name: install / upgrade k3s on master
      command: /root/install.sh server --cluster-init
      environment:
        INSTALL_K3S_EXEC: '--node-ip {{ node_ip }} --disable traefik --write-kubeconfig-mode 600 --write-kubeconfig /root/.kube/config --kubelet-arg image-gc-low-threshold=70 --kubelet-arg image-gc-high-threshold=75 --flannel-backend wireguard'
        # INSTALL_K3S_EXEC: '--node-ip {{ node_ip }} --disable traefik --node-taint "k3s-controlplane=true:NoSchedule" --write-kubeconfig-mode 600 --write-kubeconfig /root/.kube/config --kubelet-arg image-gc-low-threshold=70 --kubelet-arg image-gc-high-threshold=75 --flannel-backend wireguard'
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
      register: k3s_server
      changed_when: k3s_server.rc == 0

    - name: bash completion directory on master
      file:
        path: /etc/bash_completion.d
        state: directory
        mode: 0755

    - name: generate bash completion on master
      copy:
        content: |
          #!/bin/bash
          if [[ $(id -u) -eq 0 ]]
          then
            . <(kubectl completion bash)
            . <(crictl completion bash)
          fi
        dest: /etc/bash_completion.d/k3s
        mode: 0644

    - name: download k9s on master
      get_url:
        url: 'https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ architecture_map[ansible_architecture] }}.tar.gz'
        checksum: 'sha256:https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/checksums.txt'
        dest: /tmp/k9s.tar.gz
      register: k9s_download

    - name: uncompress k9s on master
      unarchive:
        src: /tmp/k9s.tar.gz
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
      when:
        - not ansible_check_mode
        - k9s_download is changed

    - name: wait for master node to finish
      wait_for:
        port: 6443

###############################################################################

- name: configure k3s agent node
  hosts: k3s_agents
  become: true

  tasks:
    - name: install nfs client for mounting nfs on all agents
      apt:
        name: nfs-client

    - name: mount nfs shared volume on srv
      mount:
        path: /srv
        src: '{{ nfs_ip | default( hostvars[groups["k3s_master"][0]]["node_ip"] ) }}:/srv'
        opts: tcp
        state: mounted
        fstype: nfs4

    - name: get join token form the master node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      delegate_to: '{{ groups["k3s_master"][0] }}'

    - name: prepare variables for joining master
      set_fact:
        k3s_url: '{{ hostvars[groups["k3s_master"][0]]["node_ip"] }}'
        k3s_token: '{{ k3s_token.content | b64decode | trim }}'

    - name: install / upgrade k3s on agent
      command: /root/install.sh
      environment:
        INSTALL_K3S_EXEC: '--node-ip {{ node_ip }} --kubelet-arg=image-gc-low-threshold=70 --kubelet-arg=image-gc-high-threshold=75'
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
        K3S_URL: 'https://{{ k3s_url }}:6443'
        K3S_TOKEN: '{{ k3s_token }}'
      register: k3s_server
      changed_when: k3s_server.rc == 0
