---
- name: common configuration for k3s nodes
  hosts:
    - k3s_master
    - k3s_agents
  become: true
  vars:
    docker_json:
      log-driver: json-file
      log-opts:
        max-size: 100m
      storage-driver: overlay2
        - 9.9.9.9
        - 149.112.112.112

  tasks:
    - name: set default variables
      set_fact:
        use_docker: '{{ use_docker | default(false) }}'

    - name: set legacy iptables for k3s for debian
      alternatives:
        name: '{{ item }}'
        path: '/usr/sbin/{{ item }}-legacy'
      loop:
        - iptables
        - ip6tables
      when: ansible_distribution | lower == "debian"

    - name: install python-apt
      apt:
        name: python3-apt
      check_mode: false
      when: ansible_check_mode|bool

    - name: install packages
      apt:
        name:
          - unattended-upgrades     # auto-upgrade packages
          - wireguard               # wireguard for communication between k3s nodes
        update_cache: true

    - name: export filesystes to
      set_fact:
        export_to_address: '{{ export_to_address | default(["10.42.0.0/16", "127.0.0.1/32"]) }}'
        k3s_master: '{{ groups["k3s_master"] | map("extract", hostvars, "node_ip") | list }}'
        k3s_agents: '{{ groups["k3s_agents"] | map("extract", hostvars, "node_ip") | list }}'

    # docker

    - name: install docker runtime
      apt:
        name: docker.io
      when: use_docker

    - name: configure docker
      copy:
        dest: /etc/docker/daemon.json
        content: '{{ docker_json | default({}) | to_nice_json  }}'
        mode: 0644
      register: docker_json_file
      when:
        - docker_json is defined
        - use_docker

    - name: restart docker
      systemd:
        name: docker
        enabled: true
        state: restarted
      when:
        - docker_json_file is changed
        - use_docker

    ## ufw

    - name: install ufw
      package:
        name: ufw

    - name: enable and start ufw
      systemd:
        name: ufw
        enabled: true
        state: started

    - name: ufw allow ssh
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: allow wire guard between nodes, kubernetes intercommunication
      ufw:
        rule: allow
        port: '51820'
        from: '{{ item }}'
      loop: '{{ k3s_master + k3s_agents }}'

    - name: allow internal kubernetes communication
      ufw:
        rule: allow
        from_ip: 10.42.0.0/16

    - name: allow kubernetes and pods to connect to systemd-resolv
      ufw:
        rule: allow
        port: '5355'
        from_ip: fe80::/64

    - name: allow forwarding to pods
      ini_file:
        path: /etc/default/ufw
        section: null
        option: DEFAULT_FORWARD_POLICY
        value: '"ACCEPT"'
        no_extra_spaces: true
        mode: 0644
      register: ufw_defaults

    - name: restart ufw on config change
      systemd:
        name: ufw
        state: restarted
      when: ufw_defaults is changed

    - name: enable ufw and set policy
      ufw:
        policy: reject
        state: enabled

    - name: remove swapfile from /etc/fstab
      mount:
        name: '{{ item }}'
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: get k3s install script from stable branch
      get_url:
        url: https://raw.githubusercontent.com/k3s-io/k3s/release-1.20/install.sh
        checksum: sha256:c63032985492e6fb3e7642b244a22ec7ad2f5a4f023a729de77b941dd19c6a59
        dest: /root/install.sh
        mode: 0755

###############################################################################

- name: configure k3s master node
  hosts: k3s_master
  become: true
  vars:
    architecture_map:
      aarch64: arm64
      armv7l: arm
      x86_64: x86_64

  tasks:
    - name: set default variables
      set_fact:
        k3s_version: '{{ k3s_version | default("v1.20.5+k3s1") }}'
        k9s_version: '{{ k9s_version | default("v0.24.8") }}'
        use_docker: '{{ use_docker | default(false) }}'

    - name: install nfs for serving storage to the cluster
      apt:
        name:
          - nfs-kernel-server
          - nfs-client

    - name: ufw allow kubernets api
      ufw:
        rule: allow
        port: '6443'
        proto: tcp
        from: '{{ item }}'
      loop: '{{ k3s_master + k3s_agents }}'

    - name: allow nfs from the nodes
      ufw:
        rule: allow
        port: '2049'
        from: '{{ item }}'
      loop: '{{ k3s_master + k3s_agents }}'

    - name: share /srv to the kubernetes cluster, so other nodes can start containers
      lineinfile:
        path: /etc/exports
        line: /srv {{ item }}(rw,fsid=0,sync,no_subtree_check,no_auth_nlm,insecure,no_root_squash)
        mode: 0644
      loop: '{{ k3s_master + k3s_agents }}'
      register: etc_exportfs

    - name: export filesystems through nfs
      command: exportfs -r
      when: etc_exportfs is changed

    # https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
    - name: prepare space for nfs-subdir-external-provisioner
      file:
        path: /srv/automatic-pvcs
        state: directory
        mode: a=rwxt

    - name: install / upgrade k3s on master
      command: /root/install.sh
      environment:
        INSTALL_K3S_EXEC: '{{ "--docker" if use_docker else "" }} --node-external-ip {{ node_ip }} --disable=traefik --disable local-storage --kubelet-arg=image-gc-low-threshold=70 --kubelet-arg=image-gc-high-threshold=75 --flannel-backend wireguard {{ k3s_opts | default("") }}'
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
      register: k3s_server
      changed_when: k3s_server.rc == 0

    - name: bash completion directory on master
      file:
        path: /etc/bash_completion.d
        state: directory
        mode: 0755

    - name: generate bash completion on master
      shell: '{{ item }} completion bash > /etc/bash_completion.d/{{ item }}'
      args:
        creates: '/etc/bash_completion.d/{{ item }}'
      loop:
        - kubectl
        - crictl

    - name: download k9s on master
      get_url:
        url: 'https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ architecture_map[ansible_architecture] }}.tar.gz'
        checksum: 'sha256:https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/checksums.txt'
        dest: /tmp/k9s.tar.gz
      register: k9s_download

    - name: uncompress k9s on master
      unarchive:
        src: /tmp/k9s.tar.gz
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
      when:
        - not ansible_check_mode
        - k9s_download is changed

    - name: wait for master node to finish
      wait_for:
        port: 6443

###############################################################################

- name: configure k3s agent node
  hosts: k3s_agents
  become: true

  tasks:
    - name: set default variables
      set_fact:
        k3s_version: '{{ k3s_version | default("v1.20.5+k3s1") }}'
        use_docker: '{{ use_docker | default(false) }}'

    - name: install nfs client for mounting nfs on all agents
      apt:
        name: nfs-client

    - name: get join token form the master node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      delegate_to: '{{ groups["k3s_master"][0] }}'

    - name: prepare variables for joining master
      set_fact:
        k3s_url: '{{ hostvars[groups["k3s_master"][0]]["node_ip"] }}'
        k3s_token: '{{ k3s_token.content | b64decode | trim }}'

    - name: install / upgrade k3s on agent
      command: /root/install.sh
      environment:
        INSTALL_K3S_EXEC: '{{ "--docker" if use_docker else "" }} --node-external-ip {{ node_ip }} --kubelet-arg=image-gc-low-threshold=70 --kubelet-arg=image-gc-high-threshold=75 {{ k3s_opts | default("") }}'
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
        K3S_URL: 'https://{{ k3s_url }}:6443'
        K3S_TOKEN: '{{ k3s_token }}'
      register: k3s_server
      changed_when: k3s_server.rc == 0
