# vim: ai et ts=2 st=2 sw=2 :
---
- name: homeserver configuration
  hosts: k3s_master
  become: true

  tasks:
    - name: allow other things
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: '{{ base_ufw_rules }}'

    - name: add cron jobs
      cron:
        name: '{{ item.name }}'
        weekday: '{{ item.weekday | default(omit) }}'
        day: '{{ item.day | default(omit) }}'
        minute: '{{ item.minute | default(omit) }}'
        hour: '{{ item.hour | default(omit) }}'
        user: root
        job: '{{ item.job }}'
        state: '{{ item.state | default("present") }}'
      loop: '{{ base_cron }}'
      tags:
        - cron

    - name: server ssh notify
      template:
        src: sshnotif
        dest: /usr/local/bin/sshnotif
        mode: 0755

    - name: add notify on ssh
      lineinfile:
        path: /etc/pam.d/common-session
        line: session optional pam_exec.so /usr/local/bin/sshnotif
