# vim: ai et ts=2 st=2 sw=2 :
---
- name: raspberry pi pihole
  hosts: pihole
  become: true
  vars:
    stubby_config: |
      resolution_type: GETDNS_RESOLUTION_STUB
      dns_transport_list:
        - GETDNS_TRANSPORT_TLS
      tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
      tls_query_padding_blocksize: 256
      edns_client_subnet_private : 1
      round_robin_upstreams: 0
      idle_timeout: 9000
      #timeout: 1
      #tls_backoff_time: 300
      dnssec_return_status: GETDNS_EXTENSION_TRUE
      tls_min_version: GETDNS_TLS1_3
      listen_addresses:
        - 127.0.0.1@5053
      upstream_recursive_servers:
      #  - address_data: 9.9.9.9
      #    tls_auth_name: "dns.quad9.net"
      #  - address_data: 149.112.112.112
      #    tls_auth_name: "dns.quad9.net"
      #  - address_data: 2620:fe::fe
      #    tls_auth_name: "dns.quad9.net"
      #  - address_data: 2620:fe::9
      #    tls_auth_name: "dns.quad9.net"
        - address_data: 2606:4700:4700::1111
          tls_auth_name: "cloudflare-dns.com"
        - address_data: 2606:4700:4700::1001
          tls_auth_name: "cloudflare-dns.com"
        - address_data: 1.1.1.1
          tls_auth_name: "cloudflare-dns.com"
        - address_data: 1.0.0.1
          tls_auth_name: "cloudflare-dns.com"

  tasks:
    - name: install dependencies for runnin --check
      apt:
        name:
          - python-apt
          - git
      check_mode: false

    - name: install packages
      apt:
        name:
          - dstat
          - stubby
          - ufw
          - unattended-upgrades

    - name: allow remote ssh
      ufw:
        rule: allow
        proto: '{{ item.0 }}'
        port: '{{ item.1 | string }}'
      loop:
        - - tcp
          - 22
        - - udp
          - 53
        - - tcp
          - 53
        - - udp
          - 67
        - - tcp
          - 80

    - name: enable ufw
      ufw:
        state: enabled
        direction: '{{ item.d }}'
        policy: '{{ item.p }}'
      loop:
        - d: incoming
          p: reject
        - d: outgoing
          p: allow
        - d: routed
          p: allow

    - name: hardening mss value, CVE-2019-11479
      sysctl:
        name: net.ipv4.tcp_min_snd_mss
        value: "536"

    - name: enable services
      systemd:
        name: '{{ item }}'
        state: started
        enabled: true
      loop:
        - ufw
        - stubby

    - name: add my stubby config file
      copy:
        dest: /etc/stubby/stubby.yml
        content: '{{ stubby_config }}'
        mode: 0644
      register: stubby_yml_file
      tags:
        - stubby

    - name: restart stubby server on config change
      systemd:
        name: stubby
        state: restarted
      when: stubby_yml_file is changed
      tags:
        - stubby

    - name: fetch pihole console stats script
      git:
        repo: https://github.com/pi-hole/PADD.git
        dest: /opt/padd
        version: v3.5.1
      tags:
        - git

    - name: fetch pihole
      git:
        repo: https://github.com/pi-hole/pi-hole.git
        dest: /opt/pi-hole
        version: v5.2.4
      tags:
        - git

    - name: make it possible to turn on and off wifi power management
      copy:
        dest: /etc/systemd/system/wifi_powersave@.service
        content: |
          [Unit]
          Description=Set WiFi power save %i
          After=sys-subsystem-net-devices-wlan0.device

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/sbin/iw dev wlan0 set power_save %i

          [Install]
          WantedBy=sys-subsystem-net-devices-wlan0.device
        mode: 0644

    - name: turn off wifi powersaving
      systemd:
        name: wifi_powersave@off.service
        enabled: true
        state: started
