---
- name: configure raspberian os with adafruid 2.8" screen
  hosts: piscreen
  become: true

  tasks:
    - name: Check if USER variable is defined
      assert:
        that: USER is defined
        fail_msg: "Variable USER is not defined, can't find ~USER/.ssh folder"
        success_msg: "Will search ~{{ USER|default('') }}/.ssh for public SSH keys on localhost"

    - name: find public keys
      local_action:
        module: find
        paths: '~{{ USER }}/.ssh'
        file_type: file
        use_regex: true
        patterns:
          - '^.*.pub$'
      become: '{{ USER }}'
      register: found_keys
      run_once: true

    - name: slurp public keys
      local_action:
        module: slurp
        src: '{{ item.path }}'
      become: '{{ USER }}'
      loop: '{{ found_keys.files }}'
      loop_control:
        label: '{{ item.path }}'
      register: ssh_public_keys
      run_once: true

    - name: add keys to raspberry pi, user pi
      authorized_key:
        user: pi
        key: '{{ item.content | b64decode }}'
      loop: '{{ ssh_public_keys.results }}'
      loop_control:
        label: '{{ item.content | b64decode }}'
      register: authorized_keys

    - name: remove password from rapsberry user
      user:
        name: pi
        password: '!'
      when: authorized_keys is changed

    - name: install packages
      apt:
        name:
          - python-setuptools       # allow to use the ansible pip module
          - python3-pip             # python pip and dependencies
          - wiringpi                # gpio set pin values
        cache_valid_time: 3600

    - name: install pip packages
      pip:
        name:
          - RPi.GPIO==0.7.0   # https://pypi.org/project/RPi.GPIO/
        executable: pip3

    - name: enable screen in config.txt
      blockinfile:
        marker: '# {mark} adafruid 2.8"'
        path: /boot/config.txt
        block: |
          hdmi_force_hotplug=0
          dtparam=spi=on
          dtparam=i2c1=on
          dtparam=i2c_arm=on
          dtoverlay=pitft28-resistive,rotate=90,speed=64000000,fps=30

    - name: enable screen in configure cmdline.txt
      lineinfile:
        path: /boot/cmdline.txt
        regexp: '^(.* rootwait).*$'
        line: '\1 fbcon=map:10 fbcon=font:VGA8x8'
        backrefs: true
      register: cmdline

    - name: disable terminal timeout and turn down screen brightness to 3/4
      blockinfile:
        marker: '# {mark} disable timeout and turn down brightness'
        path: /etc/rc.local
        block: |
          gpio -g mode 18 pwm
          gpio -g pwm 18 750
          sudo sh -c "TERM=linux setterm -blank 0 >/dev/tty0"
        mode: 0755
        insertbefore: '^exit.*$'

    - name: make directory for tty0
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: 0755

    - name: enable autologin on tty1
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/noclear.conf
        content: |
          # Ansible managed
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin pi --noclear %I $TERM
          TTYVTDisallocate=no
        mode: 0644

    - name: disable clearing of the terminal on getty invocation
      ini_file:
        path: /etc/systemd/system/getty@tty1.service.d/noclear.conf
        section: Service
        option: TTYVTDisallocate
        value: 'no'
        create: true
        no_extra_spaces: true
        mode: 0644

    - name: set console fonts
      ini_file:
        path: /etc/default/console-setup
        section: null
        option: '{{ item.option }}'
        value: '{{ item.value }}'
        create: true
        no_extra_spaces: true
        mode: 0644
      loop:
        - option: FONTFACE
          value: Terminus
        - option: FONTSIZE
          value: 6x12

    - name: enable sshd
      systemd:
        name: sshd
        enabled: true
        state: started

    - name: reboot raspberry pi
      reboot:
      when: cmdline is changed
