---
- name: Configure raspberian os with adafruid 2.8" screen / generic bootstrap
  hosts: piscreen
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - python-setuptools       # allow to use the ansible pip module
          - python3-pip             # python pip and dependencies
          - unattended-upgrades     # unattended upgrades
          - wiringpi                # gpio set pin values
        cache_valid_time: 3600

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - https://github.com/aheimsbakk/gpiocmd/archive/refs/tags/0.9.0.zip
        executable: pip3

    - name: Enable screen in config.txt
      ansible.builtin.blockinfile:
        marker: '# {mark} adafruid 2.8"'
        path: /boot/firmware/config.txt
        block: |
          hdmi_force_hotplug=0
          dtparam=spi=on
          dtparam=i2c1=on
          dtparam=i2c_arm=on
          dtoverlay=pitft28-resistive,rotate=90,speed=64000000,fps=30

    - name: Enable screen in configure cmdline.txt
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(.* rootwait).*$'
        line: '\1 fbcon=map:10 fbcon=font:VGA8x8 consoleblank=0'
        backrefs: true
      register: cmdline

    - name: Disable console messages from kernel
      ansible.posix.sysctl:
        name: kernel.printk
        value: '1'

    - name: Make directory for tty0
      ansible.builtin.file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: '0755'

    - name: Enable autologin on tty1
      ansible.builtin.copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          # Ansible managed
          [Service]
          ExecStart=
          ExecStart=-/usr/local/bin/gpiocmd -k -c /etc/gpiocmd.yml
          # /sbin/agetty --autologin pi --noclear %I $TERM
          StandardInput=tty
          StandardOutput=tty
          Restart=always
          RestartSec=10
          # TTYVTDisallocate=no
        mode: '0644'
      register: tty1_service

    - name: Distribute gpiocmd configuration
      ansible.builtin.copy:
        dest: /etc/gpiocmd.yml
        content: |
          {{ gpiocmd_yml | default({}) | to_nice_yaml }}
        mode: '0644'

    - name: Set console fonts
      community.general.ini_file:
        path: /etc/default/console-setup
        section: null
        option: '{{ item.option }}'
        value: '{{ item.value }}'
        create: true
        no_extra_spaces: true
        mode: '0644'
      loop:
        - option: FONTFACE
          value: Terminus
        - option: FONTSIZE
          value: 6x12

    - name: Make it possible to turn on and off wifi power management
      ansible.builtin.copy:
        dest: /etc/systemd/system/wifi_powersave@.service
        content: |
          [Unit]
          Description=Set WiFi power save %i
          After=sys-subsystem-net-devices-wlan0.device

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/sbin/iw dev wlan0 set power_save %i

          [Install]
          WantedBy=sys-subsystem-net-devices-wlan0.device
        mode: '0644'


    - name: Install packages
      ansible.builtin.apt:
        name:
          - figlet                  # fancy banners
          - jq                      # parse json
          - curl                    # talk to api
          - libnss-mdns             # zeroconfig name lookup

    - name: Copy out files
      ansible.builtin.copy:
        dest: '/opt/{{ item }}'
        src: '{{ item }}'
        mode: '0755'
      loop:
        - departure.sh

    - name: Reboot raspberry pi
      ansible.builtin.reboot:
      when: cmdline is changed or tty1_service is changed
