# vim: ai et ts=2 st=2 sw=2 :
---
- name: scripts to run on raspberry pi
  hosts: piscripts
  become: true

  tasks:
    - name: install packages
      apt:
        name:
          - figlet                  # fancy banners
          - jq                      # parse json
          - curl                    # talk to api
          - libnss-mdns             # zeroconfig name lookup

    - name: copy out files
      copy:
        dest: '/opt/{{ item }}'
        src: '{{ item }}'
        mode: 0755
      loop:
        - departure.sh
