---
- name: container munin
  hosts: podman
  become: true

  vars:
    container_customization: "{{ container_munin | default( {} ) }}"
    container_defaults:
      image: docker.io/aheimsbakk/munin-alpine
      name: munin
      generate_systemd: "{{ generate_systemd }}"
      network: dmz
      volume:
        - /srv/munin/data:/var/lib/munin:z
        - /srv/munin/conf:/etc/munin/munin-conf.d:z
        - /srv/munin/plugin_conf:/etc/munin/plugin-conf.d:z
      env:
        NODES:
        SNMP_NODES:
        TZ: UTC
      labels:
        io.containers.autoupdate: registry
        traefik.enable: "true"
        traefik.http.middlewares.munin-redirect.redirectregex.regex: "^(.+)://([^/]+)/$"
        traefik.http.middlewares.munin-redirect.redirectregex.replacement: "${1}://${2}/munin/"
        traefik.http.services.munin.loadbalancer.server.port: "80"
        traefik.http.routers.munin.entrypoints: "websecure"
        traefik.http.routers.munin.service: "munin"
        traefik.http.routers.munin.middlewares: "private-ip-ranges-no-podman,munin-redirect"

  tasks:
    - name: download and run container
      ansible.builtin.include_tasks:
        file: podman-run.yml
