---
- name: jellyfin
  hosts: podman
  become: true

  tasks:
    - name: set variables for jellyfin
      ansible.builtin.set_fact:
        jellyfin:
          volume:
            - /srv/jellyfin/config:/config
            - /srv/jellyfin/cache:/cache
            - /srv/jellyfin/media:/media
      when: jellyfin is not defined

    - name: create folders for jellyfin
      ansible.builtin.file:
        path: "{{ item | split(':') | first }}"
        owner: nobody
        state: directory
        recurse: true
      loop: "{{ jellyfin.volume }}"

    - name: download and set up jellyfin
      containers.podman.podman_container:
        image: docker.io/jellyfin/jellyfin:latest
        name: jellyfin
        network: int
        expose:
          - 8096
        user: nobody
        volume: "{{ jellyfin.volume | default(omit) }}"
        device: "{{ jellyfin.device | default(omit) }}"
        generate_systemd: "{{ generate_systemd }}"
        label:
          io.containers.autoupdate: registry
          traefik.enable: "true"
          traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
          traefik.http.routers.jellyfin.entrypoints: "websecure"


