---
- name: container prometheus and grafana
  hosts: podman
  become: true

  vars:
    container_customization_prometheus: "{{ container_prometheus | default( {} ) }}"
    container_defaults_mariadb:
      image: docker.io/mariadb:10
      name: nextcloud_mariadb
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
      user: nobody
      volume:
        - /srv/nextcloud/mariadb:/var/lib/mysql:z,U
      env: &mariadb_env
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: nextcloud
        MYSQL_HOST: nextcloud_mariadb
        MYSQL_USER: nextcloud
        MYSQL_PASSWORD: password
      network: int
      labels:
        io.containers.autoupdate: registry

    container_customization_grafana: "{{ container_grafana | default( {} ) }}"
    container_defaults_nextcloud:
      image: docker.io/aheimsbakk/nextcloud:23-apache-ffmpeg
      name: nextcloud
      volume: &nextcloud_volume
        - /srv/nextcloud/apps:/var/www/html:z
        - /srv/nextcloud/custom_apps:/var/www/html/custom_apps:z
        - /srv/nextcloud/config:/var/www/html/config:z
        - /srv/nextcloud/data:/var/www/html/data:z
      env:
        <<: *mariadb_env
        NEXTCLOUD_ADMIN_PASSWORD: password
        NEXTCLOUD_ADMIN_USER: admin
        NEXTCLOUD_DATA_DIR: /var/www/html/data
        NEXTCLOUD_TABLE_PREFIX: oc_
        NEXTCLOUD_UPDATE: 1
        NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.10.10.10.10.nip.io
        TRUSTED_PROXIES: 10.255.254.0/23
        REDIS_HOST: nextcloud_redis
      network:
        - dmz
        - int
      labels:
        io.containers.autoupdate: registry
        traefik.enable: "true"
        traefik.http.middlewares.nextcloud-redirect.redirectregex.regex: "^https://(.*)/.well-known/(card|cal)dav"
        traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement: "https://${1}/remote.php/dav/"
        traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent: "true"
        traefik.http.services.nextcloud.loadbalancer.server.port: "80"
        traefik.http.routers.nextcloud.entrypoints: "websecure"
        traefik.http.routers.nextcloud.service: "nextcloud"
        traefik.http.routers.nextcloud.middlewares: "nextcloud-redirect"


  tasks:
    - name: nextcloud_redis container
      ansible.builtin.set_fact:
        container_customization: "{{ container_prometheus }}"
        container_defaults: "{{ container_prometheus }}"

    - name: download and run container
      ansible.builtin.include_tasks:
        file: podman-run.yml

    - name: nextcloud_mariadb container
      ansible.builtin.set_fact:
        container_customization: "{{ container_grafana }}"
        container_defaults: "{{ container_grafana }}"

    - name: download and run container
      ansible.builtin.include_tasks:
        file: podman-run.yml

