---
- name: container gotify
  hosts: podman
  become: true

  vars:
    container_customization: "{{ container_gotify | default( {} ) }}"
    container_defaults:
      image: docker.io/gotify/server:2.1
      name: gotify
      network: dmz
      expose:
        - 8080
      user: nobody
      generate_systemd: "{{ generate_systemd | default(omit) }}"
      volume:
        - /srv/gotify/data:/data:z,U
      env:
        GOTIFY_SERVER_PORT: '8080'
        GOTIFY_DATABASE_DIALECT: sqlite3
        GOTIFY_DATABASE_CONNECTION: /data/gotify.db
        GOTIFY_DEFAULTUSER_NAME: admin
        GOTIFY_DEFAULTUSER_PASS: password
        GOTIFY_PASSSTRENGTH: '16'
        GOTIFY_UPLOADEDIMAGESDIR: /data/images
        GOTIFY_PLUGINSDIR: /data/plugins
        GOTIFY_SERVER_RESPONSEHEADERS: "Access-Control-Allow-Origin: \"*\"\nAccess-Control-Allow-Methods: \"GET,POST\""
      label:
        io.containers.autoupdate: registry
        traefik.enable: "true"
        traefik.http.services.gotify.loadbalancer.server.port: "8080"
        traefik.http.routers.gotify.entrypoints: "websecure"

  tasks:
    - name: download and run container
      ansible.builtin.include_tasks:
        file: podman-run.yml
