---
- name: configure podman on server
  hosts: podman
  become: true

  tasks:
    - name: install ufw
      ansible.builtin.apt:
        name: ufw

    - name: install podman and dnsmasq dependency
      ansible.builtin.apt:
        name:
          - podman
          - dnsmasq
        update_cache: yes

    - name: gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: enable ufw
      ansible.builtin.systemd:
        name: ufw
        enabled: true
        state: started
      when: "'ufw' in ansible_facts.packages"
      register: ufw_enabled

    - name: allow ssh and reject all other
      community.general.ufw:
        state: enabled
        default: reject
      when: "'ufw' in ansible_facts.packages"

    - name: allow ssh and reject all other
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp
        state: enabled
      when: "'ufw' in ansible_facts.packages"

    - name: allow incomming trafic on podman dmz
      community.general.ufw:
        rule: allow
        route: true
        from: 0.0.0.0/0
        to: 10.255.254.0/23
      when: "'ufw' in ansible_facts.packages"

    - name: enable podman socket and auto update
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - podman.socket
        - podman-auto-update.timer
      when: "'podman' in ansible_facts.packages"

    - name: exit play if podman is not installed
      ansible.builtin.meta: end_play
      when: "'podman' not in ansible_facts.packages"
      check_mode: false

    ##
    ## podman networks
    ##

    - name: create missing directory
      ansible.builtin.file:
        path: /usr/libexec/cni
        state: directory
        mode: 0755

    - name: copy dnsname plugin to correct path
      ansible.builtin.copy:
        src: /usr/lib/dnsname
        dest: /usr/libexec/cni/dnsname
        mode: 0755
        remote_src: true

    - name: podman int network
      containers.podman.podman_network:
        name: int

    - name: podman dmz network
      containers.podman.podman_network:
        name: dmz
        subnet: 10.255.254.0/23
        gateway: 10.255.254.1
        disable_dns: false


##
## include pods to start
##

- ansible.builtin.import_playbook: podman-socket.yml
- ansible.builtin.import_playbook: podman-traefik.yml
- ansible.builtin.import_playbook: podman-smokeping.yml
- ansible.builtin.import_playbook: podman-munin.yml
- ansible.builtin.import_playbook: podman-gotify.yml
- ansible.builtin.import_playbook: podman-jellyfin.yml
