# vim: ai et ts=2 st=2 sw=2 :
#
# Convert this to a role...
---
- name: configure restic for all restic sources
  hosts: restic
  become: true

  roles:
    - role: aheimsbakk.restic_backup
      restic_backup_restic_version: 0.15.2
      restic_backup_rclone_version: v1.63.1
