# vim: ai et ts=2 st=2 sw=2 :
#
# Install: python3-libvirt python3-lxml
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: Create a VM
  gather_facts: false
  hosts: localhost
  vars:
    libvirt_connection: qemu:///system
    libvirt_storage_pool: default

    state: present

    default_distros:
      trixie:
        url: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-generic-amd64.qcow2
        os_variant: debian13
        boot: uefi
      noble:
        url: https://cloud-images.ubuntu.com/minimal/daily/noble/current/noble-minimal-cloudimg-amd64.img
        os_variant: ubuntu24.04
        boot: uefi
      rocky10:
        url: https://dl.rockylinux.org/pub/rocky/10/images/x86_64/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
        os_variant: rocky-unknown
        boot: uefi
      rocky9:
        url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2
        os_variant: rocky9
        boot: uefi

    default_vm_net_config:
      version: 2
      ethernets:
        enp1s0:
          dhcp4: false
          addresses:
            - 192.168.122.10/24
          routes:
            - to: default
              via: 192.168.122.1
          nameservers:
            addresses:
              - 1.1.1.1
              - 8.8.8.8

    default_vm_config:
      memory_mb: 1024
      disk_gb: 10
      vcpus: 1
      distro: trixie
      networks:
        - bridge: virbr0
          model:
            type: virtio
      net_config: {}

    libvirt_vms:
      - name: trixie01
        memory_mb: 2000
        disk_gb: 20
        vcpus: 2
        distro: trixie
        net_config:
          ethernets:
            enp1s0:
              addresses:
                - 192.168.122.11/24
      - name: trixie02
        memory_mb: 1500
        distro: trixie
        net_config:
          ethernets:
            enp1s0:
              addresses:
                - 192.168.122.12/24
      - name: ubuntu01
        distro: noble
        networks:

    # Instances that will run, used to assemble each VMs full configuration
    running_vms: [ ]

  tasks:
    - name: Combine default and custom config for VMs with network net_config
      ansible.builtin.set_fact:
        running_vms: "{{ running_vms | default([]) + [default_vm_config | combine(item) | combine({'net_config': default_vm_net_config}) | combine(item, recursive=True)] }}"
      loop: "{{ libvirt_vms }}"
      loop_control:
        label: '{{ item.name }}'
      when: item.net_config is defined and item.net_config != {}

    - name: Combine default and custom config for the rest
      ansible.builtin.set_fact:
        running_vms: "{{ running_vms | default([]) + [default_vm_config | combine(item)] }}"
      loop: "{{ libvirt_vms }}"
      loop_control:
        label: '{{ item.name }}'
      when: item.net_config | default({}) == {}

    - name: Set temporary variables for cloud image information
      ansible.builtin.set_fact:
        cloud_image_name: "{{ default_distros[item.distro]['url'] | basename }}"
        cloud_image_url: "{{ default_distros[item.distro]['url'] }}"
        cloud_image_sha: "{{ default_distros[item.distro]['sha'] | default(omit) }}"
      loop: "{{ running_vms }}"
      loop_control:
        label: '{{ item.name }}'
      register: cloud_images_information

    - name: Find unique cloud images to download, and ready to download
      ansible.builtin.set_fact:
        cloud_images_unique: "{{ cloud_images_information.results | map(attribute='ansible_facts') | unique | list }}"
        temp_folder: /tmp

    - name: Download local copy of cloud images
      ansible.builtin.get_url:
        url: "{{ item.cloud_image_url }}"
        dest: "{{ temp_folder }}/{{ item.cloud_image_name }}"
        mode: '0644'
        checksum: "{{ item.cloud_image_sha | default(omit) }}"
      loop: "{{ cloud_images_unique }}"
      loop_control:
        label: '{{ item.cloud_image_url }}'

    - name: Create disk placeholder in storage pool
      ansible.builtin.command:
        argv:
          - virsh
          - --connect
          - "{{ libvirt_connection }}"
          - vol-create-as
          - "{{ libvirt_storage_pool }}"
          - "{{ item.name }}.qcow2"
          - "{{ item.disk_gb }}G"
          - --format
          - qcow2
      loop: "{{ running_vms }}"
      register: disk_placeholder
      loop_control:
        label: '{{ item.name }}.qcow2'
      ignore_errors: true
      failed_when: false
      changed_when: false
      when: state == "present"

    - name: List new placeholders in storage pool
      ansible.builtin.command: echo
      loop: "{{ disk_placeholder.results }}"
      loop_control:
        label: '{{ item.item.name }}.qcow2'
      changed_when: true
      when:
        - state == "present"
        - item.rc == 0

    - name: Import cloud image into placeholder
      ansible.builtin.command:
        argv:
          - virsh
          - --connect
          - "{{ libvirt_connection }}"
          - vol-upload
          - "{{ item.item.name }}.qcow2"
          - "{{ temp_folder }}/{{ default_distros[item.item.distro]['url'] | basename }}"
          - --sparse
          - --pool
          - "{{ libvirt_storage_pool }}"
      loop: "{{ disk_placeholder.results }}"
      loop_control:
        label: '{{ item.item.name }}.qcow2'
      changed_when: true
      when:
        - state == "present"
        - item.rc == 0

    - name: Resize VM disk
      ansible.builtin.command:
        argv:
          - virsh
          - --connect
          - "{{ libvirt_connection }}"
          - vol-resize
          - "{{ item.item.name }}.qcow2"
          - "{{ item.item.disk_gb }}G"
          - --pool
          - "{{ libvirt_storage_pool }}"
      loop: "{{ disk_placeholder.results }}"
      loop_control:
        label: '{{ item.item.name }}.qcow2'
      changed_when: true
      when:
        - state == "present"
        - item.rc == 0

    - name: Create temporary network config file
      ansible.builtin.tempfile:
        state: file
        suffix: ansible
      register: temp_net_config
      loop: "{{ running_vms }}"
      loop_control:
        label: '{{ item.name }}'

    - name: Populate temporary network config file
      ansible.builtin.copy:
        dest: "{{ item.path }}"
        mode: "0600"
        content: |
          {{ item.item.net_config | to_nice_yaml }}
      loop: "{{ temp_net_config.results }}"
      loop_control:
        label: '{{ item.item.name }}'
      when:
        - item.item.net_config | default({}) != {}

    - name: Create VMs
      community.libvirt.virt_install:
        uri: "{{ libvirt_connection }}"
        name: "{{ item.item.name }}"
        memory: "{{ item.item.memory_mb }}"
        vcpus: "{{ item.item.vcpus }}"
        import: true
        osinfo:
          name: "{{ default_distros[item.item.distro]['os_variant'] }}"
        boot: "{{ default_distros[item.item.distro]['boot'] | default(omit) }}"
        disks:
          - vol: "{{ libvirt_storage_pool }}/{{ item.item.name }}.qcow2"
            bus: virtio
            driver:
              discard: unmap
        cloud_init:
          disable: true
          root_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
          network_config: "{{ item.path | default(omit) }}"
        networks: "{{ item.item.networks | default(omit) }}"
        graphics:
          type: none
        state: "{{ state }}"
      loop: "{{ temp_net_config.results }}"
      loop_control:
        label: '{{ item.item.name }}'
      failed_when: false
      # when: state == "present"

    - name: Undefine VMs
      community.libvirt.virt:
        name: "{{ item.item.name }}"
        command: undefine
        flags:
          - nvram
      loop: "{{ temp_net_config.results }}"
      loop_control:
        label: '{{ item.item.name }}'
      failed_when: false
      when: state == "absent"

    - name: Remove temporary network config file
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ temp_net_config.results }}"
      loop_control:
        label: '{{ item.item.name }}'
      when: item.path is defined
