# vim: ai et ts=2 st=2 sw=2 :
#
# How to run this playbook:
# $ ansible-playbook -K dekstop.yml
---
- name: configure fedora desktop
  hosts: localhost
  become: true

  tasks:
    - name: run only on fedora
      assert:
        that: ansible_distribution == "Fedora"

    - name: rpmfusion repositories
      dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        disable_gpg_check: true

    # - name: add tainted repo (libdvdcss)
    #   dnf:
    #     name: rpmfusion-free-release-tainted

    - name: install packages
      dnf:
        name:
          - ansible-core      # Automate everything
          - ansible-lint      # Lint everything
          - arm-image-installer  # Install arm images, ie. fedora arm on a SD-card
          - catimg            # Display images in terminal
          - dstat             # Stat system values in colors
          - ffmpeg            # Transcode audio and video
          - flac              # Lossless audio
          - lame              # Encode mp3
          - lftp              # FTP isn't dead
          - libmp4v2          # AAXtoMP3 dep
          - ltrace            # Trace library calls
          - mediainfo         # AAXto MP3 dep
          - nmap              # Scan network ports
          - offlineimap       # Make local backup of IMAP
          - pv                # How fast do we transfer
          - python3-boto      # S3 library for Duplicity
          - python3-pygments  # Syntax highlighting in Hugo
          - python3-qrcode    # Generate QR-codes in terminal with qr
          - rsync             # Syncing files, syncing life
          - strace            # String trace processes
          - tmux              # <3
          - vim               # <3
          - whois             # A must
          - yamllint          # YAML files need to be linted too
          - zmap              # Map internet

