---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: traefik
  name: traefik
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-m1
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists

# apiVersion: v1
# kind: Service
# namespace: traefik
# metadata:
#   name: traefik
# spec:
#   externalIPs:
#   # - 192.168.1.20
