---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  template:
    spec:
      nodeSelector:
        k3s.io/hostname: k3s-m1


#apiVersion: v1
#kind: Service
#namespace: traefik
#metadata:
#  name: traefik
#spec:
#  externalIPs:
#  # - 192.168.1.20
#
