---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: forgejo-backup
  labels:
    app: forgejo
spec:
  schedule: "3 13 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: cron-forgejo
          restartPolicy: Never
          containers:
            - name: forgejo-backup
              image: docker.io/alpine:latest
              command:
                - /bin/sh
              args:
                - -c
                - |
                  apk --no-cache add sqlite ;
                  cd /data/gitea ;
                  echo == VACUUM ;
                  sqlite3 gitea.db "PRAGMA wal_checkpoint;" ;
                  sqlite3 gitea.db "VACUUM;" ;
                  echo == BACKUP ;
                  sqlite3 gitea.db ".backup gitea-backup-$(date -Is | tr : -).db" ;
                  ls gitea-backup* ;
                  echo == DELETE OLDER THAN 7 DAYS ;
                  find . -type f -maxdepth 1 -mtime +7 -name 'gitea-backup-*.db' -delete ;
                  ls gitea-backup*
              volumeMounts:
                - name: forgejo-data
                  mountPath: /data
          volumes:
            - name: forgejo-data
              hostPath:
                type: DirectoryOrCreate
                path: /srv/forgejo/data
