---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-forgejo
  labels:
    app: forgejo

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cron-forgejo
  labels:
    app: forgejo
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cron-forgejo
  labels:
    app: forgejo
subjects:
  - kind: ServiceAccount
    name: cron-forgejo
    apiGroup: ""
roleRef:
  kind: Role
  name: cron-forgejo
  apiGroup: ""
