---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-update-pods
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: auto-update-pods
            egress: internal
        spec:
          serviceAccountName: cron-pod-updater
          restartPolicy: Never
          containers:
            - name: kubectl
              image: docker.io/rancher/k3s:latest
              command:
                - /bin/sh
              args:
                - -c
                - for i in $(kubectl get deployments -o name -l auto-update-hour=$(date +%H)); do kubectl patch $i -p '{"spec":{"template":{"metadata":{"labels":{"restarted-by":"'${POD_NAME}'"}}}}}'; done; sleep 60
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
