---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
    # Se /etc/cdi/intel.yaml, dette er en direkte CDI referanse, old reference
    # io.podman.annotations.device: "intel.com/gpu=all"
  labels:
    app: jellyfin-pod
  name: jellyfin-pod
spec:
  automountServiceAccountToken: false
  enableServiceLinks: false
  containers:
  - image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096
      hostPort: 8096
    # Indirekte CDI referanse, som er for podman 5.4 og nyere.
    resources:
      limits:
        intel.com/gpu=all: 1
    securityContext:
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      runAsGroup: 65534
      runAsUser: 65534
    volumeMounts:
    - mountPath: /config
      name: config-path
    - mountPath: /cache
      name: cache-path
    - mountPath: /media
      name: mnt-path
      readOnly: true
  volumes:
  - hostPath:
      path: /srv/jellyfin/config
      type: Directory
    name: config-path
  - hostPath:
      path: /srv/jellyfin/cache
      type: Directory
    name: cache-path
  - hostPath:
      path: /mnt
      type: Directory
    name: mnt-path
