---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - config/tls-mintls12.yaml
      - config/tls-mintls13.yaml
      - config/middleware-default-https-headers.yaml
      - config/middleware-private-ip-ranges.yaml
      - config/middleware-munin-redirect.yaml
      - config/middleware-nextcloud-redirect.yaml
      - config/middleware-auth-private-service.yaml
      - config/router-traefik.yaml
      - config/router-metrics.yaml
      - config/middleware-rate200in1min.yaml
      - config/router-forgejo-ssh.yaml
    name: traefik-config
resources:
  - rbac.yml
  - deployment.yml
  - ingress.yml
