---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokeping
  labels:
    app: smokeping
    auto-update-hour: '00'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeping
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smokeping
    spec:
      containers:
        - name: smokeping
          image: docker.io/aheimsbakk/smokeping:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: smokeping-config
              mountPath: /etc/smokeping
            - name: smokeping-data
              mountPath: /var/lib/smokeping
          env:
            - name: TZ
              value: UTC
          ports:
            - name: web
              containerPort: 80
          securityContext:
            capabilities:
              add:
                - net_admin
                - net_raw
            # allowPrivilegeEscalation: false
      volumes:
        - name: smokeping-config
          hostPath:
            type: DirectoryOrCreate
            path: /srv/smokeping/config
        - name: smokeping-data
          hostPath:
            type: DirectoryOrCreate
            path: /srv/smokeping/data

---
apiVersion: v1
kind: Service
metadata:
  name: smokeping
spec:
  selector:
    app: smokeping
  ports:
    - protocol: TCP
      name: web
      port: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: smokeping
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: private-ip-ranges@file
  labels:
    app: smokeping
spec:
  rules:
    - host: smokeping.192.168.56.11.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smokeping
                port:
                  number: 80
