---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-pod-updater

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cron-pod-updater
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "patch", "get", "list" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cron-pod-updater
subjects:
  - kind: ServiceAccount
    name: cron-pod-updater
    apiGroup: ""
roleRef:
  kind: Role
  name: cron-pod-updater
  apiGroup: ""
