---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - config/prometheus.yml
    name: prometheus-config
patchesStrategicMerge:
  - targets-traefik.yml
resources:
  - rbac.yml
  - deployment.yml
