---
namespace: default
resources:
  # - ../../base/gitlab
  # - ../../base/forgejo
  # - ../../base/searxng
  - ../../base/gotify
  - ../../base/munin
  - ../../base/nextcloud
  - ../../base/smokeping
  - ../../base/pod-updater
  - ../../base/prometheus
  - ../../base/grafana
  - ../../base/vaultwarden
  - ../../base/collabora
  - default-netpol.yml
