---
namespace: default
resources:
  # - ../../base/diun
  # - ../../base/gitlab
  - ../../base/gotify
  - ../../base/munin
  - ../../base/nextcloud
  - ../../base/smokeping
  - ../../base/pod-updater
  - ../../base/prometheus
  - ../../base/grafana
  - ../../base/vaultwarden
  - ../../base/collabora
  - netpol.yml