---
apiVersion: v1
kind: Secret
metadata:
  name: etherpad
  labels:
    app: etherpad
type: Opaque
stringData:
  ADMIN_PASSWORD: password
  MYSQL_USER: etherpad
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad-mysql
  labels:
    app: etherpad-mysql
    auto-update-hour: '00'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etherpad-mysql
    spec:
      containers:
        - name: etherpad-mysql
          image: docker.io/mariadb:10
          imagePullPolicy: Always
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --innodb-file-per-table=1
            - --log-bin
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MYSQL_DATABASE
              value: etherpad
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: MYSQL_ROOT_PASSWORD
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            # capabilities:
            #   drop: [ "all" ]
            #   add: [ "chown" ]
          ports:
            - name: etherpad-mysql
              containerPort: 3306
      volumes:
        - name: mysql-data
          hostPath:
            path: /srv/etherpad/mysql
            type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: etherpad-mysql
  labels:
    app: etherpad-mysql
spec:
  selector:
    app: etherpad-mysql
  ports:
    - protocol: TCP
      name: mysql
      port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
  labels:
    app: etherpad
    auto-update-hour: '00'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      initContainers:
        - name: etherpad-init
          image: docker.io/alpine:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              chmod a+rwt /data
          volumeMounts:
            - name: etherpad-data
              mountPath: /data
      containers:
        - name: etherpad
          image: docker.io/etherpad/etherpad:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: ADMIN_PASSWORD
            - name: DB_TYPE
              value: 'mysql'
            - name: DB_HOST
              value: etherpad-mysql
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: etherpad
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: MYSQL_PASSWORD
            - name: SKIN_VARIANTS
              value: 'dark-toolbar super-light-editor dark-background'
            - name: PAD_OPTIONS_USE_MONOSPACE_FONT
              value: 'true'
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: [ "all" ]
          ports:
            - name: web
              containerPort: 9001
          volumeMounts:
            - name: etherpad-data
              mountPath: /opt/etherpad-lite/var
      volumes:
        - name: etherpad-data
          hostPath:
            type: DirectoryOrCreate
            path: /srv/etherpad/data

---
apiVersion: v1
kind: Service
metadata:
  name: etherpad
  labels:
    app: etherpad
spec:
  selector:
    app: etherpad
  ports:
    - protocol: TCP
      name: web
      port: 9001

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: etherpad
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    app: etherpad
spec:
  rules:
    - host: etherpad.192.168.56.11.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: etherpad
                port:
                  number: 9001

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: etherpad-admin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: private-ip-ranges@file
  labels:
    app: etherpad
spec:
  rules:
    - host: etherpad.192.168.56.11.nip.io
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: etherpad
                port:
                  number: 9001
