---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: traefik
data:
  tls-mintls12.yaml: |
    tls:
      options:
        mintls12:
          minVersion: VersionTLS12
          cipherSuites:
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

  tls-mintls13.yaml: |
    tls:
      options:
        mintls13:
          minVersion: VersionTLS13

  middleware-default-https-headers.yaml: |
    http:
      middlewares:
        default-https-headers:
          headers:
            customFrameOptionsValue: SAMEORIGIN
            frameDeny: true
            sslRedirect: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            referrerPolicy: same-origin

  middleware-private-ip-ranges.yaml: |
    http:
      middlewares:
        private-ip-ranges:
          ipWhiteList:
            sourceRange:
              - 192.168.0.0/16
              - 172.16.0.0/12
              - 10.0.0.0/8

  middleware-munin-redirect.yaml: |
    http:
      middlewares:
        munin-redirect:
          redirectRegex:
            regex: ^(.+)://([^/]+)/$
            replacement: ${1}://${2}/munin/

  middleware-nextcloud-redirect.yaml: |
    http:
      middlewares:
        nextcloud-redirect:
          redirectRegex:
            regex: ^https://(.*)/.well-known/(card|cal)dav
            replacement: https://${1}/remote.php/dav/
            permanent: true

  middleware-auth-private-service.yaml: |
    http:
      middlewares:
        auth-private-service:
          basicAuth:
            users:
              - "admin:$apr1$nZpuakhI$Eng/oKsoxryF87IwbDSYO0"

  router-traefik.yaml: |
    http:
      routers:
        dashboard:
          rule: Host(`traefik.10.20.30.11.xip.io`)
          service: api@internal
          middlewares:
            - auth-private-service
          entryPoints:
            - websecure
