---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: build

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
  namespace: build
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "secrets" ]
    verbs: [ "create", "get", "list", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
  namespace: build
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    apiGroup: ""
roleRef:
  kind: Role
  name: gitlab-runner
  apiGroup: ""
