---
http:
  middlewares:
    default-https-headers:
      headers:
        customFrameOptionsValue: SAMEORIGIN
        frameDeny: true
        # sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
