##
## homeserver base
##

# { "port": "8080", "proto": "tcp" }
base_ufw_rules: []

# { "name": "my cron job", "minute": 0, "hour": "*/2", "job": "echo"  }
base_cron: []


##
## notify on ssh
##

gotify_domain: gotify.10.0.0.10.nip.io
gotify_token: TOKEN

##
## fail2ban
##

fail2ban_jail_d:
  sshd:
    enabled: true
    banaction: hostsdeny
    maxretry: 5
    findtime: 10m
    bantime: 10m
    mode: aggressive
  recidive:
    enabled: true
    findtime: 1d
    bantime: 1w
    banaction: ufw
    maxretry: 3


