{
 "title": "Ganglia Statistics Overview",
 "description": "Generisk dashboard for cluster statistikk á la Ganglia",
 "tags": [
  "stats",
  "ganglia"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, env)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\"}, datacenter)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\", datacenter=~\"$datacenter\"}, zone)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\", datacenter=~\"$datacenter\", zone=~\"$zone\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\", datacenter=~\"$datacenter\", zone=~\"$zone\", service=~\"$service\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$instance\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "count(up{instance=~\"$instance\"}) - sum(up{instance=~\"$instance\"})",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[$__rate_interval])) + avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"steal\"}[$__rate_interval])))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Relative Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load15{instance=~\"$instance\"}) / sum(count by(instance)(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}))",
     "legendFormat": "15-min"
    },
    {
     "expr": "sum(node_load5{instance=~\"$instance\"}) / sum(count by(instance)(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}))",
     "legendFormat": "5-min"
    },
    {
     "expr": "sum(node_load1{instance=~\"$instance\"}) / sum(count by(instance)(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}))",
     "legendFormat": "1-min"
    }
   ]
  },
  {
   "title": "Load 15-min distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cluster Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$instance\"})",
     "legendFormat": "Load 1-min"
    },
    {
     "expr": "sum(up{instance=~\"$instance\"})",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(count by(instance)(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}))",
     "legendFormat": "CPUs"
    },
    {
     "expr": "sum(node_procs_running{instance=~\"$instance\"})",
     "legendFormat": "Procs"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) - sum(node_memory_MemFree_bytes{instance=~\"$instance\"}) - sum(node_memory_Buffers_bytes{instance=~\"$instance\"}) - sum(node_memory_Cached_bytes{instance=~\"$instance\"}) - sum(node_memory_Slab_bytes{instance=~\"$instance\"}) - sum(node_memory_PageTables_bytes{instance=~\"$instance\"}) - sum(node_memory_SwapCached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Use"
    },
    {
     "expr": "sum(node_memory_PageTables_bytes{instance=~\"$instance\"})",
     "legendFormat": "Page tables"
    },
    {
     "expr": "sum(node_memory_SwapCached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Swap cached"
    },
    {
     "expr": "sum(node_memory_Slab_bytes{instance=~\"$instance\"})",
     "legendFormat": "Slab"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{instance=~\"$instance\"})",
     "legendFormat": "Buffer"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"$instance\"})",
     "legendFormat": "Unused"
    },
    {
     "expr": "sum(node_memory_HardwareCorrupted_bytes{instance=~\"$instance\"})",
     "legendFormat": "Corrupted"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$instance\"}) - sum(node_memory_SwapFree_bytes{instance=~\"$instance\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(node_memory_Committed_AS_bytes{instance=~\"$instance\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"user\"}[$__rate_interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"nice\"}[$__rate_interval]))",
     "legendFormat": "Nice"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"system\"}[$__rate_interval]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"iowait\"}[$__rate_interval]))",
     "legendFormat": "IOWait"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"irq\"}[$__rate_interval]))",
     "legendFormat": "IRQ"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"softirq\"}[$__rate_interval]))",
     "legendFormat": "SoftIRQ"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"steal\"}[$__rate_interval]))",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_reads_merged_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read merged"
    },
    {
     "expr": "sum(rate(node_disk_writes_merged_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Write merged"
    }
   ]
  },
  {
   "title": "Disk bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Aggregated load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregated Load 1-min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Down status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "count by(instance)(up{instance=~\"$instance\"} == 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$instance\"})",
     "legendFormat": "Load 1-min"
    },
    {
     "expr": "sum(count by(instance)(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}))",
     "legendFormat": "CPUs"
    },
    {
     "expr": "sum(node_procs_running{instance=~\"$instance\"})",
     "legendFormat": "Procs"
    }
   ]
  }
 ]
}