{
 "title": "Ganglia Statistics Detail",
 "tags": [
  "ganglia",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, env)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\"}, datacenter)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\", datacenter=~\"$datacenter\"}, zone)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\", datacenter=~\"$datacenter\", zone=~\"$zone\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", env=~\"$env\", datacenter=~\"$datacenter\", zone=~\"$zone\", service=~\"$service\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "Load 1-min"
    },
    {
     "expr": "count by(instance)(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "CPUs"
    },
    {
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "Procs"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(mode)(rate(node_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemFree_bytes{instance=~\"$instance\"} - node_memory_Buffers_bytes{instance=~\"$instance\"} - node_memory_Cached_bytes{instance=~\"$instance\"} - node_memory_Slab_bytes{instance=~\"$instance\"} - node_memory_PageTables_bytes{instance=~\"$instance\"} - node_memory_SwapCached_bytes{instance=~\"$instance\"} ",
     "legendFormat": "Use"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$instance\"}",
     "legendFormat": "Page tables"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Swap cached"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$instance\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"$instance\"})",
     "legendFormat": "Unused"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$instance\"}",
     "legendFormat": "Corrupted"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"} - node_memory_SwapFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$instance\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=~\"$instance\"} / node_filesystem_size_bytes{instance=~\"$instance\"}) * 100",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "Disk bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_reads_merged_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read merged"
    },
    {
     "expr": "sum(rate(node_disk_writes_merged_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Write merged"
    }
   ]
  },
  {
   "title": "Interupts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_intr_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Interupts"
    }
   ]
  }
 ]
}